SELECT b.HID,b.PACK_DOC_HID,b.DOC_NAME,b.DOC_HID,b.CONTENT,b.DATTR,b.UN,b.NAM_KLIENT,b.PHID,
       (SELECT GROUP_CONCAT(bt.TO_NAM_KLIENT ORDER BY bt.TO_NAM_KLIENT SEPARATOR ' | ') AS TNK
        FROM BOARDTALK_TO_UN bt WHERE bt.HID_BT=b.HID) AS TO_NAM_KLIENTS
FROM BOARDTALK b WHERE b.PACK_DOC_HID=? AND b.DOC_NAME=? AND b.DOC_HID=? ORDER BY b.DATTR