SELECT k.HID, k.NKON, k.DOTP, k.MASSA_BRUTTO_ALL,
       (SELECT GROUP_CONCAT(pl.ZNAK SEPARATOR ', ') AS PLOMB
        FROM KY_PLOMB pl
        WHERE pl.HID_KONT = k.HID
        ORDER BY pl.SORT) AS PLOMB,
       k.MASSA_TAR, k.POD_SILA, k.VID
FROM KY_KONT k WHERE k.HID_VAGON = ? AND k.HID_CLIENT = ?
