package com.bivc.cimsmgs.db.ky;

// Generated 19.02.2014 14:19:48 by Hibernate Tools 3.4.0.CR1

import com.bivc.cimsmgs.formats.json.serializers.DateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 * Vagon generated by hbm2java
 */

public class Vagon implements Serializable, Comparable<Vagon> {

    private Long hid;
    private Poezd poezd;
    private String trans;

    private Date dattr;
    private String un;

    private Date altered;


    private String nvag;
    private Byte koleya;

    private Date dprb;

    private Date dotp;

    private Byte direction;
    private Short sort;
    private Set<Kont> kontsOut = new TreeSet<>();
    private Set<Kont> kontsInto = new TreeSet<>();
    private String kpv;
    private Integer kolOs;
    private Long masTar;
    private String sobstv;

    @JsonSerialize(using = DateSerializer.class)
    private Date bortDate;
    private String prim;
    private Long probeg;
    private Float podSila;

    private Date plan_rem;
    private Date reviz;
    private Long type_no;
    private Float dlina;
    private String model;
    private String line;
    private String foot;
    private Boolean poruz;
    private Boolean defective;
    private NsiKyOwners owner;

    public NsiKyOwners getOwner() {
        return owner;
    }

    public void setOwner(NsiKyOwners owner) {
        this.owner = owner;
    }

    public Boolean getDefective() {
        return defective;
    }

    public void setDefective(Boolean defective) {
        this.defective = defective;
    }

    public Boolean getPoruz() {
        return poruz;
    }

    public void setPoruz(Boolean poruz) {
        this.poruz = poruz;
    }

    public String getFoot() {
        return foot;
    }

    public void setFoot(String foot) {
        this.foot = foot;
    }

    public String getLine() {
        return line;
    }

    public void setLine(String line) {
        this.line = line;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public Float getDlina() {
        return dlina;
    }

    public void setDlina(Float dlina) {
        this.dlina = dlina;
    }

    public Long getType_no() {
        return type_no;
    }

    public void setType_no(Long type_no) {
        this.type_no = type_no;
    }

    public Date getReviz() {
        return reviz;
    }

    public void setReviz(Date reviz) {
        this.reviz = reviz;
    }

    public Date getPlan_rem() {
        return plan_rem;
    }

    public void setPlan_rem(Date plan_rem) {
        this.plan_rem = plan_rem;
    }

    public enum FilterFields{
        NPPR("nppr"),
        NVAG("nvag")
        ;
        private final String name;

        FilterFields(String name){
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    public Float getPodSila() {
        return podSila;
    }

    public void setPodSila(Float podSila) {
        this.podSila = podSila;
    }

    public Long getProbeg() {
        return probeg;
    }

    public void setProbeg(Long probeg) {
        this.probeg = probeg;
    }

    public String getPrim() {
        return prim;
    }

    public void setPrim(String prim) {
        this.prim = prim;
    }

    public Date getBortDate() {
        return bortDate;
    }

    public void setBortDate(Date bortDate) {
        this.bortDate = bortDate;
    }

    public String getSobstv() {
        return sobstv;
    }

    public void setSobstv(String sobstv) {
        this.sobstv = sobstv;
    }

    public Long getMasTar() {
        return masTar;
    }

    public void setMasTar(Long masTar) {
        this.masTar = masTar;
    }

    public Integer getKolOs() {
        return kolOs;
    }

    public void setKolOs(Integer kolOs) {
        this.kolOs = kolOs;
    }

    public String getKpv() {
        return kpv;
    }

    public void setKpv(String kpv) {
        this.kpv = kpv;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toStringExclude(this, "kontsOut", "kontsInto", "poezd");
    }

    public Vagon() {
    }

    public Vagon(Long hid) {
        this.hid = hid;
    }

    public Vagon(Long hid, Poezd poezd, String trans, Date dattr, String un, Date altered, String nvag, Byte koleya, Date dprb, Date dotp,
                 Byte direction, Short sort, Set<Kont> kontsOut, Set<Kont> kontsInto) {
        this.hid = hid;
        this.poezd = poezd;
        this.trans = trans;
        this.dattr = dattr;
        this.un = un;
        this.altered = altered;
        this.nvag = nvag;
        this.koleya = koleya;
        this.dprb = dprb;
        this.dotp = dotp;
        this.direction = direction;
        this.sort = sort;
        this.kontsOut = kontsOut;
        this.kontsInto = kontsInto;
    }

    public Long getHid() {
        return this.hid;
    }

    public void setHid(Long hid) {
        this.hid = hid;
    }

    public Poezd getPoezd() {
        return this.poezd;
    }

    public void setPoezd(Poezd poezd) {
        this.poezd = poezd;
    }

    public String getTrans() {
        return this.trans;
    }

    public void setTrans(String trans) {
        this.trans = trans;
    }

    public Date getDattr() {
        return this.dattr;
    }

    public void setDattr(Date dattr) {
        this.dattr = dattr;
    }

    public String getUn() {
        return this.un;
    }

    public void setUn(String un) {
        this.un = un;
    }

    public Date getAltered() {
        return this.altered;
    }

    public void setAltered(Date altered) {
        this.altered = altered;
    }

    public String getNvag() {
        return this.nvag;
    }

    public void setNvag(String nvag) {
        this.nvag = nvag;
    }

    public Byte getKoleya() {
        return this.koleya;
    }

    public void setKoleya(Byte koleya) {
        this.koleya = koleya;
    }

    public Date getDprb() {

        /*if (this.dprbDate != null) {
            this.dprb = this.dprbDate;
            if (this.dprbTime != null) {
                this.dprb = DateTimeUtils.addTimeToDate(this.dprbDate, this.dprbTime);
            }
        }*/
        return this.dprb;
    }

    public void setDprb(Date dprb) {
        this.dprb = dprb;
    }

    public Date getDotp() {

        /*if (this.dotpDate != null) {
            this.dotp = this.dotpDate;
            if (this.dotpTime != null) {
                this.dotp = DateTimeUtils.addTimeToDate(this.dotpDate, this.dotpTime);
            }
        }*/
        return this.dotp;
    }

    public void setDotp(Date dotp) {
        this.dotp = dotp;
    }

    public Byte getDirection() {
        return this.direction;
    }

    public void setDirection(Byte direction) {
        this.direction = direction;
    }

    public Short getSort() {
        return this.sort;
    }

    public void setSort(Short sort) {
        this.sort = sort;
    }

    public Set<Kont> getKontsOut() {
        return this.kontsOut;
    }

    public void setKontsOut(Set<Kont> kontsOut) {
        this.kontsOut = kontsOut;
    }

    public Set<Kont> getKontsInto() {
        return this.kontsInto;
    }

    public void setKontsInto(Set<Kont> kontsInto) {
        this.kontsInto = kontsInto;
    }


    @Override
    public int compareTo(Vagon that) {
        final int BEFORE = -1;
        final int AFTER = 1;

        if (that == null) {
            return BEFORE;
        }

        Comparable thisHid = this.getHid();
        Comparable thatHid = that.getHid();

        if(thisHid == null) {
            return AFTER;
        } else if(thatHid == null) {
            return BEFORE;
        } else {
            return thisHid.compareTo(thatHid);
        }
    }
}
