SELECT KGVN, IFNULL(c.CARGO_FULLNAME, NZGR) AS NZGR, CAST(KOLM AS UNSIGNED) AS PLACES, MNET AS MASSA FROM VAG_PER_VED v
LEFT JOIN CARGO_GNG_PL c ON v.KGVN=c.CARGO_GROUP
WHERE HID=? AND (NKON IS NULL OR LENGTH(NKON) = 0) AND KGVN NOT LIKE '992%'
