SELECT v.HID AS HID_KONT, kk.MASSA_TAR, kk.POD_SILA, kk.VID, kk.TYPE
FROM VAG_PER_VED v
         LEFT JOIN KY_KONT kk ON CONCAT(v.PRIN,v.NKON)=kk.`NKON` AND kk.HID = (SELECT MAX(kk2.HID) FROM `KY_KONT` kk2 WHERE kk2.NKON=kk.NKON AND kk2.MASSA_TAR IS NOT NULL GROUP BY kk2.NKON)
WHERE v.NKON IS NOT NULL AND LENGTH(v.NKON) > 0 AND v.N_POEZD=? AND v.N_PACKET=? AND v.VED_NOMER=? AND v.NVAG=?
