SELECT p.HID, p.UN, p.ALTERED, p.DATTR, p.TRANS, p.KOLEYA, p.DIRECTION, p.HID_CLIENT, p.GRUZOTPR, p.DPRB,
       COUNT(DISTINCT v.HID) AS COUNT_VAG, MAX(v.SORT) AS MAX_SORT_VAG
FROM KY_POEZD p
    LEFT JOIN KY_VAGON v ON p.HID=v.HID_POEZD
WHERE p.HID=?
GROUP BY p.HID, p.UN, p.ALTERED, p.DATTR, p.TRANS, p.KOLEYA, p.DIRECTION, p.HID_CLIENT, p.GRUZOTPR, p.DPRB