SELECT NVAG AS nvag, GROUP_CONCAT(CONCAT(PRIN,NKON) SEPARATOR ', ') AS nkon, GROUP_CONCAT(SMGS SEPARATOR ', ') AS smgs, MAX(NPOL) AS npol,
COUNT(CASE WHEN NKON IS NULL OR LENGTH(NKON) = 0 THEN NULL ELSE '1' END) AS cnkon       
FROM VAG_PER_VED WHERE N_POEZD=? AND N_PACKET=? AND VED_NOMER=?
GROUP BY N_POEZD, N_PACKET, VED_NOMER, NVAG, POR_VAG
ORDER BY CAST(POR_VAG AS UNSIGNED)