SELECT MAX(v.HID) AS HID_VAG, MAX(kv.KOL_OS) AS KOL_OS, MAX(kv.MAS_TAR) AS MAS_TAR, MAX(kv.POD_SILA) AS POD_SILA
FROM VAG_PER_VED v
         LEFT JOIN KY_VAGON kv ON v.NVAG=kv.NVAG AND kv.HID = (SELECT MAX(kv2.HID) FROM KY_VAGON kv2 WHERE kv2.NVAG=kv.NVAG AND kv2.POD_SILA IS NOT NULL GROUP BY kv2.NVAG)
WHERE v.N_POEZD=? AND v.N_PACKET=? AND v.VED_NOMER=? AND v.NVAG=?
GROUP BY v.N_POEZD, v.N_PACKET, v.VED_NOMER, v.NVAG, v.POR_VAG
ORDER BY CAST(v.POR_VAG AS UNSIGNED)