SELECT v.HID, v.NVAG, v.POD_SILA, v.MAS_TAR, v.KOL_OS,
       CASE WHEN EXISTS (SELECT k.HID FROM KY_KONT k WHERE k.HID_VAGON=v.HID) OR EXISTS (SELECT g.HID FROM KY_GRUZ g WHERE g.HID_VAGON=v.HID) THEN 'L' ELSE 'P' END AS PORUZ
FROM KY_VAGON v WHERE v.HID_POEZD=?