package com.bivc.cimsmgs.db;

// Generated 10.02.2010 14:28:43 by Hibernate Tools 3.2.5.Beta

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.Date;

/**
 * CimSmgsPlatel generated by hbm2java
 */
@JsonIgnoreProperties({ "cimSmgs"})
public class CimSmgsPlatel implements Serializable {

	private Long hid;
	private CimSmgs cimSmgs;
	private String dor;
	private String plat;
	private String prim;
	private Date dattr;
	private Date locked;
	private String unLock;
	private Byte sort;
	private String kplat;
	private String kplat1;
	private String kplat2;
	private String kplat3;
	private String dorR;
	private String platR;
	private String primR;
	private String strana;
	private byte flag;
    private String primR1;

	public CimSmgsPlatel() {
	}

	public CimSmgsPlatel(Long hid, Byte sort) {
		this.hid = hid;
		this.sort = sort;
	}

	public CimSmgsPlatel(Long hid, CimSmgs cimSmgs, String dor,
			String plat, String prim, Date dattr, Date locked, String unLock,
            Byte sort, String kplat, String kplat1, String kplat2,
			String kplat3, String dorR, String platR, String primR,
			String strana, byte flag) {
		this.hid = hid;
		this.cimSmgs = cimSmgs;
		this.dor = dor;
		this.plat = plat;
		this.prim = prim;
		this.dattr = dattr;
		this.locked = locked;
		this.unLock = unLock;
		this.sort = sort;
		this.kplat = kplat;
		this.kplat1 = kplat1;
		this.kplat2 = kplat2;
		this.kplat3 = kplat3;
		this.dorR = dorR;
		this.platR = platR;
		this.primR = primR;
		this.strana = strana;
		this.flag = flag;
	}

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}
	@JsonBackReference
	public CimSmgs getCimSmgs() {
		return this.cimSmgs;
	}
	@JsonBackReference
	public void setCimSmgs(CimSmgs cimSmgs) {
		this.cimSmgs = cimSmgs;
	}

	public String getDor() {
		return this.dor;
	}

	public void setDor(String dor) {
		this.dor = dor;
	}

	public String getPlat() {
		return this.plat;
	}

	public void setPlat(String plat) {
		this.plat = plat;
	}

	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public Date getLocked() {
		return this.locked;
	}

	public void setLocked(Date locked) {
		this.locked = locked;
	}

	public String getUnLock() {
		return this.unLock;
	}

	public void setUnLock(String unLock) {
		this.unLock = unLock;
	}

	public Byte getSort() {
		return this.sort;
	}

	public void setSort(Byte sort) {
		this.sort = sort;
	}

	public String getKplat() {
		return this.kplat;
	}

	public void setKplat(String kplat) {
		this.kplat = kplat;
	}

	public String getKplat1() {
		return this.kplat1;
	}

	public void setKplat1(String kplat1) {
		this.kplat1 = kplat1;
	}

	public String getKplat2() {
		return this.kplat2;
	}

	public void setKplat2(String kplat2) {
		this.kplat2 = kplat2;
	}

	public String getKplat3() {
		return this.kplat3;
	}

	public void setKplat3(String kplat3) {
		this.kplat3 = kplat3;
	}

	public String getDorR() {
		return this.dorR;
	}

	public void setDorR(String dorR) {
		this.dorR = dorR;
	}

	public String getPlatR() {
		return this.platR;
	}

	public void setPlatR(String platR) {
		this.platR = platR;
	}

	public String getPrimR() {
		return this.primR;
	}

	public void setPrimR(String primR) {
		this.primR = primR;
	}

	public String getStrana() {
		return this.strana;
	}

	public void setStrana(String strana) {
		this.strana = strana;
	}

	public byte getFlag() {
		return this.flag;
	}

	public void setFlag(byte flag) {
		this.flag = flag;
	}

    public String getPrimR1() {
        return primR1;
    }

    public void setPrimR1(String primR1) {
        this.primR1 = primR1;
    }
}
