package com.bivc.cimsmgs.db;

// Generated 01.11.2011 8:57:21 by Hibernate Tools 3.4.0.CR1

import com.bivc.cimsmgs.commons.myUser;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CimSmgsFileInf generated by hbm2java
 */
@JsonIgnoreProperties({"packDoc","route","cimSmgsFiles"})
public class CimSmgsFileInf implements Serializable {

	private Long hid;
	private Route route;
	private PackDoc packDoc;
	private String type;
	private String nkon;
	private Date dattr;
	private String un;
	private Set<CimSmgsFile> cimSmgsFiles = new HashSet<CimSmgsFile>(0);
    private String trans;

    public String getTrans() {
        return trans;
    }

    public void setTrans(String trans) {
        this.trans = trans;
    }

    public CimSmgsFileInf() {
	}

	public CimSmgsFileInf(Long hid, Date dattr, String un) {
		this.hid = hid;
		this.dattr = dattr;
		this.un = un;
	}

	public CimSmgsFileInf(Long hid, Route route, PackDoc packDoc, String type,
			String nkon, Date dattr, String un, Set cimSmgsFiles) {
		this.hid = hid;
		this.route = route;
		this.packDoc = packDoc;
		this.type = type;
		this.nkon = nkon;
		this.dattr = dattr;
		this.un = un;
		this.cimSmgsFiles = cimSmgsFiles;
	}

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public PackDoc getPackDoc() {
		return this.packDoc;
	}

	public void setPackDoc(PackDoc packDoc) {
		this.packDoc = packDoc;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNkon() {
		return this.nkon;
	}

	public void setNkon(String nkon) {
		this.nkon = nkon;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

	public Set getCimSmgsFiles() {
		return this.cimSmgsFiles;
	}

	public void setCimSmgsFiles(Set cimSmgsFiles) {
		this.cimSmgsFiles = cimSmgsFiles;
	}

    public boolean hasPack(){
        return this.getPackDoc() != null && this.getPackDoc().getHid() != null;
    }

    public void insertNewPacket(myUser user){
        PackDoc pack = new PackDoc();
        pack.setRoute(getRoute());
        pack.setUsrGroupsDir(user.getUsr().getGroup());
        pack.addFileInfItem(this);
    }

    public void preparePacket(myUser user){
        getPackDoc().setRoute(getRoute());
        getPackDoc().setUsrGroupsDir(user.getUsr().getGroup());
        getPackDoc().addFileInfItem(this);
    }

    public void prepare4save(myUser user) {
//        if(!hasPack()){
//            insertNewPacket(user);
//        }
//        else {
//            preparePacket(user);
//        }
        setDattr(new Date());
		setUn(user.getUsername());
		setTrans(user.getUsr().getGroup().getName());
    }

	public void addFileItem(CimSmgsFile f) {
		if (f != null) {
			f.setCimSmgsFileInf(this);
			cimSmgsFiles.add(f);
		}
	}


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CimSmgsFileInf that = (CimSmgsFileInf) o;
        return Objects.equals(hid, that.hid) &&
                Objects.equals(route != null ? route.getHid() : "", that.route != null ? that.route.getHid() : "") &&
                Objects.equals(packDoc!= null ? packDoc.getHid() : "", that.packDoc != null ? that.packDoc.getHid() : "") &&
                Objects.equals(type, that.type) &&
                Objects.equals(nkon, that.nkon) &&
                Objects.equals(un, that.un) &&
                Objects.equals(trans, that.trans);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hid, route != null ? route.getHid() : "", packDoc!= null ? packDoc.getHid() : "", type, nkon, un, trans);
    }
}
