package com.bivc.cimsmgs.db;

// Generated 01.11.2011 8:57:21 by Hibernate Tools 3.4.0.CR1

import com.bivc.cimsmgs.commons.myUser;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CimSmgsFileInf generated by hbm2java
 */
@JsonIgnoreProperties({"packDoc","route","cimSmgsFiles"})
public class CimSmgsFileInf implements Serializable {

	private Long hid;
	private Route route;
	private PackDoc packDoc;
	private String type;
	private String nkon;
	private Date dattr;
	private String un;
	private Set<CimSmgsFile> cimSmgsFiles = new HashSet<CimSmgsFile>(0);
    private String trans;

    public String getTrans() {
        return trans;
    }

    public void setTrans(String trans) {
        this.trans = trans;
    }

    public CimSmgsFileInf() {
	}

	public CimSmgsFileInf(Long hid, Date dattr, String un) {
		this.hid = hid;
		this.dattr = dattr;
		this.un = un;
	}

	public CimSmgsFileInf(Long hid, Route route, PackDoc packDoc, String type,
			String nkon, Date dattr, String un, Set cimSmgsFiles) {
		this.hid = hid;
		this.route = route;
		this.packDoc = packDoc;
		this.type = type;
		this.nkon = nkon;
		this.dattr = dattr;
		this.un = un;
		this.cimSmgsFiles = cimSmgsFiles;
	}

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public PackDoc getPackDoc() {
		return this.packDoc;
	}

	public void setPackDoc(PackDoc packDoc) {
		this.packDoc = packDoc;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNkon() {
		return this.nkon;
	}

	public void setNkon(String nkon) {
		this.nkon = nkon;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

	public Set getCimSmgsFiles() {
		return this.cimSmgsFiles;
	}

	public void setCimSmgsFiles(Set cimSmgsFiles) {
		this.cimSmgsFiles = cimSmgsFiles;
	}

    public boolean hasPack(){
        return this.getPackDoc() != null && this.getPackDoc().getHid() != null;
    }

    public void insertNewPacket(myUser user){
        PackDoc pack = new PackDoc();
        pack.setRoute(getRoute());
        pack.setUsrGroupsDir(user.getUsr().getGroup());
        pack.addFileInfItem(this);
    }

    public void preparePacket(myUser user){
        getPackDoc().setRoute(getRoute());
        getPackDoc().setUsrGroupsDir(user.getUsr().getGroup());
        getPackDoc().addFileInfItem(this);
    }

    public void prepare4save(myUser user) {
//        if(!hasPack()){
//            insertNewPacket(user);
//        }
//        else {
//            preparePacket(user);
//        }
        setDattr(new Date());
		setUn(user.getUsername());
		setTrans(user.getUsr().getGroup().getName());
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        CimSmgsFileInf that = (CimSmgsFileInf) o;

        return new EqualsBuilder()
                .append(hid, that.hid)
                .append(route, that.route)
                .append(packDoc, that.packDoc)
                .append(type, that.type)
                .append(nkon, that.nkon)
                .append(dattr, that.dattr)
                .append(un, that.un)
                .append(trans, that.trans)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(hid)
                .append(route)
                .append(packDoc)
                .append(type)
                .append(nkon)
                .append(dattr)
                .append(un)
                .append(trans)
                .toHashCode();
    }
}
