package com.bivc.cimsmgs.db;

// Generated 27.05.2009 10:04:59 by Hibernate Tools 3.2.4.GA

import com.bivc.cimsmgs.db.nsi.Company;

/**
 * CimSmgsStatusAllowed generated by hbm2java
 */
public class CimSmgsStatusAllowed implements java.io.Serializable {

	private Long hid;
	private Company company;
	private CimSmgs cimSmgs;
  private Byte sort;

  public CimSmgsStatusAllowed() {
	}

	public CimSmgsStatusAllowed(Long hid, Company company, CimSmgs cimSmgs, Byte sort) {
		this.hid = hid;
		this.company = company;
		this.cimSmgs = cimSmgs;
    this.sort = sort;
	}

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public CimSmgs getCimSmgs() {
		return this.cimSmgs;
	}

  public Byte getSort()
  {
    return sort;
  }

  public void setCimSmgs(CimSmgs cimSmgs) {
		this.cimSmgs = cimSmgs;
	}

  public void setSort(Byte sort)
  {
    this.sort = sort;
  }

}
