package com.bivc.cimsmgs.db;

// Generated 26.02.2013 14:32:44 by Hibernate Tools 3.4.0.CR1

/**
 * Doc2docTemplsRouteRefs generated by hbm2java
 */
public class Doc2docTemplsRouteRefs implements java.io.Serializable {

	private Doc2docTemplsRouteRefsId id;
	private Route route;
	private Doc2docTemplates doc2docTemplates;

	public Doc2docTemplsRouteRefs() {
	}

	public Doc2docTemplsRouteRefs(Doc2docTemplsRouteRefsId id, Route route, Doc2docTemplates doc2docTemplates) {
		this.id = id;
		this.route = route;
		this.doc2docTemplates = doc2docTemplates;
	}

	public Doc2docTemplsRouteRefsId getId() {
		return this.id;
	}

	public void setId(Doc2docTemplsRouteRefsId id) {
		this.id = id;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public Doc2docTemplates getDoc2docTemplates() {
		return this.doc2docTemplates;
	}

	public void setDoc2docTemplates(Doc2docTemplates doc2docTemplates) {
		this.doc2docTemplates = doc2docTemplates;
	}

}
