package com.bivc.cimsmgs.db;

// Generated 26.02.2013 14:32:44 by Hibernate Tools 3.4.0.CR1

/**
 * Doc2docTemplsRouteUnRefsId generated by hbm2java
 */
public class Doc2docTemplsRouteUnRefsId implements java.io.Serializable {

	private long hidDoc2doc;
	private String hidUn;
	private Long hidRoute;

	public Doc2docTemplsRouteUnRefsId() {
	}

	public Doc2docTemplsRouteUnRefsId(long hidDoc2doc, String hidUn, Long hidRoute) {
		this.hidDoc2doc = hidDoc2doc;
		this.hidUn = hidUn;
		this.hidRoute = hidRoute;
	}

	public long getHidDoc2doc() {
		return this.hidDoc2doc;
	}

	public void setHidDoc2doc(long hidDoc2doc) {
		this.hidDoc2doc = hidDoc2doc;
	}

	public String getHidUn() {
		return this.hidUn;
	}

	public void setHidUn(String hidUn) {
		this.hidUn = hidUn;
	}

	public Long getHidRoute() {
		return this.hidRoute;
	}

	public void setHidRoute(Long hidRoute) {
		this.hidRoute = hidRoute;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Doc2docTemplsRouteUnRefsId))
			return false;
		Doc2docTemplsRouteUnRefsId castOther = (Doc2docTemplsRouteUnRefsId) other;

		return (this.getHidDoc2doc() == castOther.getHidDoc2doc())
				&& ((this.getHidUn() == castOther.getHidUn()) || (this.getHidUn() != null && castOther.getHidUn() != null && this.getHidUn().equals(
						castOther.getHidUn())))
				&& ((this.getHidRoute() == castOther.getHidRoute()) || (this.getHidRoute() != null && castOther.getHidRoute() != null && this
						.getHidRoute().equals(castOther.getHidRoute())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHidDoc2doc();
		result = 37 * result + (getHidUn() == null ? 0 : this.getHidUn().hashCode());
		result = 37 * result + (getHidRoute() == null ? 0 : this.getHidRoute().hashCode());
		return result;
	}

}
