package com.bivc.cimsmgs.db;

// Generated 26.02.2013 14:32:44 by Hibernate Tools 3.4.0.CR1

/**
 * Doc2docTemplsRouteRefsId generated by hbm2java
 */
public class Doc2docTemplsRouteRefsId implements java.io.Serializable {

	private long hidDoc2doc;
	private Long hidRoute;

	public Doc2docTemplsRouteRefsId() {
	}

	public Doc2docTemplsRouteRefsId(long hidDoc2doc, Long hidRoute) {
		this.hidDoc2doc = hidDoc2doc;
		this.hidRoute = hidRoute;
	}

	public long getHidDoc2doc() {
		return this.hidDoc2doc;
	}

	public void setHidDoc2doc(long hidDoc2doc) {
		this.hidDoc2doc = hidDoc2doc;
	}

	public Long getHidRoute() {
		return this.hidRoute;
	}

	public void setHidRoute(Long hidRoute) {
		this.hidRoute = hidRoute;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Doc2docTemplsRouteRefsId))
			return false;
		Doc2docTemplsRouteRefsId castOther = (Doc2docTemplsRouteRefsId) other;

		return (this.getHidDoc2doc() == castOther.getHidDoc2doc())
				&& ((this.getHidRoute() == castOther.getHidRoute()) || (this.getHidRoute() != null && castOther.getHidRoute() != null && this
						.getHidRoute().equals(castOther.getHidRoute())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHidDoc2doc();
		result = 37 * result + (getHidRoute() == null ? 0 : this.getHidRoute().hashCode());
		return result;
	}

}
