package com.bivc.cimsmgs.db;

// Generated 15.11.2012 11:12:37 by Hibernate Tools 3.4.0.CR1

/**
 * DocsFobiddenUsrGroupsId generated by hbm2java
 */
public class DocsFobiddenUsrGroupsId implements java.io.Serializable {

	private Long docHid;
	private String groupName;

	public DocsFobiddenUsrGroupsId() {
	}

	public DocsFobiddenUsrGroupsId(Long docHid, String groupName) {
		this.docHid = docHid;
		this.groupName = groupName;
	}

	public Long getDocHid() {
		return this.docHid;
	}

	public void setDocHid(Long docHid) {
		this.docHid = docHid;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocsFobiddenUsrGroupsId))
			return false;
		DocsFobiddenUsrGroupsId castOther = (DocsFobiddenUsrGroupsId) other;

		return ((this.getDocHid() == castOther.getDocHid()) || (this.getDocHid() != null && castOther.getDocHid() != null && this.getDocHid().equals(
				castOther.getDocHid())))
				&& ((this.getGroupName() == castOther.getGroupName()) || (this.getGroupName() != null && castOther.getGroupName() != null && this
						.getGroupName().equals(castOther.getGroupName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocHid() == null ? 0 : this.getDocHid().hashCode());
		result = 37 * result + (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		return result;
	}

}
