package com.bivc.cimsmgs.db;

// Generated 15.11.2012 11:12:37 by Hibernate Tools 3.4.0.CR1


/**
 * DocsFobiddenUsrGroups generated by hbm2java
 */
public class DocsFobiddenUsrGroups implements java.io.Serializable {

	private DocsFobiddenUsrGroupsId id;
	private DocDir docDir;
	private UsrGroupsDir usrGroupsDir;

	public DocsFobiddenUsrGroups() {
	}

	public DocsFobiddenUsrGroups(DocsFobiddenUsrGroupsId id, DocDir docDir, UsrGroupsDir usrGroupsDir) {
		this.id = id;
		this.docDir = docDir;
		this.usrGroupsDir = usrGroupsDir;
	}

	public DocsFobiddenUsrGroupsId getId() {
		return this.id;
	}

	public void setId(DocsFobiddenUsrGroupsId id) {
		this.id = id;
	}

	public DocDir getDocDir() {
		return this.docDir;
	}

	public void setDocDir(DocDir docDir) {
		this.docDir = docDir;
	}

	public UsrGroupsDir getUsrGroupsDir() {
		return this.usrGroupsDir;
	}

	public void setUsrGroupsDir(UsrGroupsDir usrGroupsDir) {
		this.usrGroupsDir = usrGroupsDir;
	}

}
