package com.bivc.cimsmgs.db;

// Generated 13.11.2012 10:12:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * FieldsDocsRefs generated by hbm2java
 */
public class FieldsDocsRefs implements Serializable {

	private FieldsDocsRefsId id;
	private FieldsDir fieldsDir;
	private DocDir docDir;
    private String descr;

    public String getDescr() {
        return descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public FieldsDocsRefs() {
	}

	public FieldsDocsRefs(FieldsDocsRefsId id, FieldsDir fieldsDir, DocDir docDir) {
		this.id = id;
		this.fieldsDir = fieldsDir;
		this.docDir = docDir;
	}

	public FieldsDocsRefsId getId() {
		return this.id;
	}

	public void setId(FieldsDocsRefsId id) {
		this.id = id;
	}

	public FieldsDir getFieldsDir() {
		return this.fieldsDir;
	}

	public void setFieldsDir(FieldsDir fieldsDir) {
		this.fieldsDir = fieldsDir;
	}

	public DocDir getDocDir() {
		return this.docDir;
	}

	public void setDocDir(DocDir docDir) {
		this.docDir = docDir;
	}

}
