package com.bivc.cimsmgs.db;

// Generated 13.11.2012 10:12:54 by Hibernate Tools 3.4.0.CR1

/**
 * FieldsAccessFobiddenId generated by hbm2java
 */
public class FieldsAccessFobiddenId implements java.io.Serializable {

	private Long fieldHid;
	private Long docHid;
	private String groupName;

	public FieldsAccessFobiddenId() {
	}

	public FieldsAccessFobiddenId(Long fieldHid, Long docHid, String groupName) {
		this.fieldHid = fieldHid;
		this.docHid = docHid;
		this.groupName = groupName;
	}

	public Long getFieldHid() {
		return this.fieldHid;
	}

	public void setFieldHid(Long fieldHid) {
		this.fieldHid = fieldHid;
	}

	public Long getDocHid() {
		return this.docHid;
	}

	public void setDocHid(Long docHid) {
		this.docHid = docHid;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FieldsAccessFobiddenId))
			return false;
		FieldsAccessFobiddenId castOther = (FieldsAccessFobiddenId) other;

		return ((this.getFieldHid() == castOther.getFieldHid()) || (this.getFieldHid() != null && castOther.getFieldHid() != null && this
				.getFieldHid().equals(castOther.getFieldHid())))
				&& ((this.getDocHid() == castOther.getDocHid()) || (this.getDocHid() != null && castOther.getDocHid() != null && this.getDocHid()
						.equals(castOther.getDocHid())))
				&& ((this.getGroupName() == castOther.getGroupName()) || (this.getGroupName() != null && castOther.getGroupName() != null && this
						.getGroupName().equals(castOther.getGroupName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFieldHid() == null ? 0 : this.getFieldHid().hashCode());
		result = 37 * result + (getDocHid() == null ? 0 : this.getDocHid().hashCode());
		result = 37 * result + (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		return result;
	}

}
