package com.bivc.cimsmgs.db;

// Generated 05.05.2012 14:42:49 by Hibernate Tools 3.4.0.CR1

/**
 * LoggingEventException generated by hbm2java
 */
public class LoggingEventException implements java.io.Serializable {

	private LoggingEventExceptionId id;
	private LoggingEvent loggingEvent;
	private String traceLine;

	public LoggingEventException() {
	}

	public LoggingEventException(LoggingEventExceptionId id,
			LoggingEvent loggingEvent, String traceLine) {
		this.id = id;
		this.loggingEvent = loggingEvent;
		this.traceLine = traceLine;
	}

	public LoggingEventExceptionId getId() {
		return this.id;
	}

	public void setId(LoggingEventExceptionId id) {
		this.id = id;
	}

	public LoggingEvent getLoggingEvent() {
		return this.loggingEvent;
	}

	public void setLoggingEvent(LoggingEvent loggingEvent) {
		this.loggingEvent = loggingEvent;
	}

	public String getTraceLine() {
		return this.traceLine;
	}

	public void setTraceLine(String traceLine) {
		this.traceLine = traceLine;
	}

}
