package com.bivc.cimsmgs.db;

// Generated 05.05.2012 14:42:49 by Hibernate Tools 3.4.0.CR1

/**
 * LoggingEventPropertyId generated by hbm2java
 */
public class LoggingEventPropertyId implements java.io.Serializable {

	private Long eventId;
	private String mappedKey;

	public LoggingEventPropertyId() {
	}

	public LoggingEventPropertyId(long eventId, String mappedKey) {
		this.eventId = eventId;
		this.mappedKey = mappedKey;
	}

	public long getEventId() {
		return this.eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	public String getMappedKey() {
		return this.mappedKey;
	}

	public void setMappedKey(String mappedKey) {
		this.mappedKey = mappedKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoggingEventPropertyId))
			return false;
		LoggingEventPropertyId castOther = (LoggingEventPropertyId) other;

		return (this.getEventId() == castOther.getEventId())
				&& ((this.getMappedKey() == castOther.getMappedKey()) || (this
						.getMappedKey() != null
						&& castOther.getMappedKey() != null && this
						.getMappedKey().equals(castOther.getMappedKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEventId();
		result = 37 * result
				+ (getMappedKey() == null ? 0 : this.getMappedKey().hashCode());
		return result;
	}

}
