package com.bivc.cimsmgs.db;

// Generated 21.12.2012 10:26:32 by Hibernate Tools 3.4.0.CR1

/**
 * MailSettings generated by hbm2java
 */
public class MailSettings implements java.io.Serializable {

	private Long hid;
	private String sender;
	private String mailServer;
	private String username;
	private String password;

	public MailSettings() {
	}

	public MailSettings(Long hid, String sender, String mailServer, String username, String password) {
		this.hid = hid;
		this.sender = sender;
		this.mailServer = mailServer;
		this.username = username;
		this.password = password;
	}

	public long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getMailServer() {
		return this.mailServer;
	}

	public void setMailServer(String mailServer) {
		this.mailServer = mailServer;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
