package com.bivc.cimsmgs.db;

// Generated 02.06.2011 11:17:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * NsiCurrency generated by hbm2java
 */
public class NsiCurrency implements java.io.Serializable {

	private BigDecimal hid;
	private Date dattr;
	private Date locked;
	private String unLock;
	private String trans;
	private String un;
	private Date deleted;
	private Date altered;
	private String kod;
	private String abv3;
	private String name;

	public NsiCurrency() {
	}

	public NsiCurrency(BigDecimal hid, Date dattr, Date altered) {
		this.hid = hid;
		this.dattr = dattr;
		this.altered = altered;
	}

	public NsiCurrency(BigDecimal hid, Date dattr, Date locked, String unLock, String trans, String un, Date deleted, Date altered, String kod,
			String abv3, String name) {
		this.hid = hid;
		this.dattr = dattr;
		this.locked = locked;
		this.unLock = unLock;
		this.trans = trans;
		this.un = un;
		this.deleted = deleted;
		this.altered = altered;
		this.kod = kod;
		this.abv3 = abv3;
		this.name = name;
	}

	public BigDecimal getHid() {
		return this.hid;
	}

	public void setHid(BigDecimal hid) {
		this.hid = hid;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public Date getLocked() {
		return this.locked;
	}

	public void setLocked(Date locked) {
		this.locked = locked;
	}

	public String getUnLock() {
		return this.unLock;
	}

	public void setUnLock(String unLock) {
		this.unLock = unLock;
	}

	public String getTrans() {
		return this.trans;
	}

	public void setTrans(String trans) {
		this.trans = trans;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	public Date getAltered() {
		return this.altered;
	}

	public void setAltered(Date altered) {
		this.altered = altered;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public String getAbv3() {
		return this.abv3;
	}

	public void setAbv3(String abv3) {
		this.abv3 = abv3;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
