package com.bivc.cimsmgs.db;
// Generated 16.01.2012 14:17:16 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * NsiDir generated by hbm2java
 */
public class NsiDir implements Serializable {


    private BigDecimal hid;
    private String name;
    private String descr;
    private Boolean zipped;

    public Boolean isZipped() {
        return zipped;
    }

    public void setZipped(Boolean zipped) {
        this.zipped = zipped;
    }

    public NsiDir() {
    }


    public NsiDir(BigDecimal hid) {
        this.hid = hid;
    }

    public NsiDir(BigDecimal hid, String name, String descr) {
        this.hid = hid;
        this.name = name;
        this.descr = descr;
    }

    public BigDecimal getHid() {
        return this.hid;
    }

    public void setHid(BigDecimal hid) {
        this.hid = hid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }


}


