package com.bivc.cimsmgs.db;
// Generated 07.12.2011 10:07:37 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;

/**
 * NsiDeliv generated by hbm2java
 */
public class NsiDeliv  implements java.io.Serializable {


     private BigDecimal hid;
     private String kod;
     private String dnameR;
     private String dnameCh;
     private String dnameEn;

    public NsiDeliv() {
    }

	
    public NsiDeliv(BigDecimal hid) {
        this.hid = hid;
    }
    public NsiDeliv(BigDecimal hid, String kod, String dnameR, String dnameCh, String dnameEn) {
       this.hid = hid;
       this.kod = kod;
       this.dnameR = dnameR;
       this.dnameCh = dnameCh;
       this.dnameEn = dnameEn;
    }
   
    public BigDecimal getHid() {
        return this.hid;
    }
    
    public void setHid(BigDecimal hid) {
        this.hid = hid;
    }
    public String getKod() {
        return this.kod;
    }
    
    public void setKod(String kod) {
        this.kod = kod;
    }
    public String getDnameR() {
        return this.dnameR;
    }
    
    public void setDnameR(String dnameR) {
        this.dnameR = dnameR;
    }
    public String getDnameCh() {
        return this.dnameCh;
    }
    
    public void setDnameCh(String dnameCh) {
        this.dnameCh = dnameCh;
    }
    public String getDnameEn() {
        return this.dnameEn;
    }
    
    public void setDnameEn(String dnameEn) {
        this.dnameEn = dnameEn;
    }




}


