package com.bivc.cimsmgs.db;

// Generated 14.09.2012 11:14:43 by Hibernate Tools 3.4.0.CR1

import com.bivc.cimsmgs.actions.PrintTemplates_A;
import com.bivc.cimsmgs.commons.myUser;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrintBlank generated by hbm2java
 */
public class PrintBlank implements Serializable {

	private Long hid;
	private DocDir docDir;
	private String name;
	private Blob data;
	private Date dattr;
	private String un;
	private String trans;
	private Date altered;
	private Byte page;
	private Set<PrintBlankTemplRef> printBlankTemplRefs = new HashSet<PrintBlankTemplRef>(0);
    private String fileName;
    private String contentType;
    private BigDecimal length;
    private Byte ncopy;

    public Byte getNcopy() {
        return ncopy;
    }

    public void setNcopy(Byte ncopy) {
        this.ncopy = ncopy;
    }

    /*private Map<Byte,PrintBlankTemplRef> printBlankTemplRefs = new TreeMap<Byte, PrintBlankTemplRef>();

        public Map<Byte,PrintBlankTemplRef> getPrintBlankTemplRefs() {
            return printBlankTemplRefs;
        }

        public void setPrintBlankTemplRefs(Map<Byte,PrintBlankTemplRef> printBlankTemplRefs) {
            this.printBlankTemplRefs = printBlankTemplRefs;
        }
    */
    public BigDecimal getLength() {
        return length;
    }

    public void setLength(BigDecimal length) {
        this.length = length;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public PrintBlank() {
	}

	public PrintBlank(Long hid, DocDir docDir, String name, Blob data, Date dattr, String un, String trans, Date altered, byte page, byte ncopy) {
		this.hid = hid;
		this.docDir = docDir;
		this.name = name;
		this.data = data;
		this.dattr = dattr;
		this.un = un;
		this.trans = trans;
		this.altered = altered;
		this.page = page;
        this.ncopy = ncopy;
	}

	public PrintBlank(Long hid, DocDir docDir, String name, Blob data, Date dattr, String un, String trans, Date altered, byte page, byte ncopy, /*Map<Byte,PrintBlankTemplRef> printBlankTemplRefs,*/
			Set printBlankTemplRefs) {
		this.hid = hid;
		this.docDir = docDir;
		this.name = name;
		this.data = data;
		this.dattr = dattr;
		this.un = un;
		this.trans = trans;
		this.altered = altered;
		this.page = page;
		this.printBlankTemplRefs = printBlankTemplRefs;
        this.ncopy = ncopy;
	}

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public DocDir getDocDir() {
		return this.docDir;
	}

	public void setDocDir(DocDir docDir) {
		this.docDir = docDir;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Blob getData() {
		return this.data;
	}

	public void setData(Blob data) {
		this.data = data;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

	public String getTrans() {
		return this.trans;
	}

	public void setTrans(String trans) {
		this.trans = trans;
	}

	public Date getAltered() {
		return this.altered;
	}

	public void setAltered(Date altered) {
		this.altered = altered;
	}

	public byte getPage() {
		return this.page;
	}

	public void setPage(byte page) {
		this.page = page;
	}

	public Set<PrintBlankTemplRef> getPrintBlankTemplRefs() {
		return this.printBlankTemplRefs;
	}

	public void setPrintBlankTemplRefs(Set<PrintBlankTemplRef> printBlankTemplRefs) {
		this.printBlankTemplRefs = printBlankTemplRefs;
	}

    public void prepare4save(myUser user, PrintTemplates_A printTemplates_a) {
        setDattr(new Date());
        setAltered(new Date());
        setUn(user.getUsername());
        setTrans(user.getUsr().getGroup().getName());

        setFileName(printTemplates_a.getUploadFileName());
        setContentType(printTemplates_a.getUploadContentType());
        setLength(new BigDecimal(printTemplates_a.getUpload().length()));
    }
}
