package com.bivc.cimsmgs.db;

// Generated 12.07.2012 14:46:29 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.*;

/**
 * PrintTemplates generated by hbm2java
 */
@JsonIgnoreProperties({"docDir","routePrintTemplateses","routeUnPrintTemplateses","printDatas","printBlankTemplRefs"})
public class PrintTemplates implements Serializable {
//    @JsonSerialize(include = JsonSerialize.Inclusion.ALWAYS)
	private Long hid;
	private DocDir docDir;
	private String name;
	private Date dattr;
	private String un;
	private String trans;
	private Date altered;
	private boolean defaults;
    private Set<RoutePrintTemplates> routePrintTemplateses = new HashSet<RoutePrintTemplates>(0);
    private Set<RouteUnPrintTemplates> routeUnPrintTemplateses = new HashSet<RouteUnPrintTemplates>(0);
    private Set<PrintBlankTemplRef> printBlankTemplRefs = new HashSet<PrintBlankTemplRef>(0);
//    private Set<PrintData> printDatas = new HashSet<PrintData>(0);
    private List<PrintData> printDat = new ArrayList<PrintData>();

    private Map<Integer, PrintData> printDatas = new TreeMap<Integer, PrintData>();

    private boolean defaultable;
    private float paperWidth;
    private float paperHeight;
    private byte fontSize;
    private String fontFamily;
    private Byte leading;
    private boolean sync;

    public boolean isSync() {
        return sync;
    }

    public void setSync(boolean sync) {
        this.sync = sync;
    }


    public Set<PrintBlankTemplRef> getPrintBlankTemplRefs() {
        return printBlankTemplRefs;
    }

    public void setPrintBlankTemplRefs(Set<PrintBlankTemplRef> printBlankTemplRefs) {
        this.printBlankTemplRefs = printBlankTemplRefs;
    }

    public Map<Integer, PrintData> getPrintDatas() {
        return printDatas;
    }

    public void setPrintDatas(Map<Integer, PrintData> printDatas) {
        this.printDatas = printDatas;
    }

    public Byte getLeading() {
        return leading;
    }

    public void setLeading(Byte leading) {
        this.leading = leading;
    }

    public String getFontFamily() {
        return fontFamily;
    }

    public void setFontFamily(String fontFamily) {
        this.fontFamily = fontFamily;
    }
//    private boolean bold;
//    private boolean uppercase;

//    public boolean isUppercase() {
//        return uppercase;
//    }
//
//    public void setUppercase(boolean uppercase) {
//        this.uppercase = uppercase;
//    }
//
//    public boolean isBold() {
//        return bold;
//    }
//
//    public void setBold(boolean bold) {
//        this.bold = bold;
//    }

    public byte getFontSize() {
        return fontSize;
    }

    public void setFontSize(byte fontSize) {
        this.fontSize = fontSize;
    }

    public float getPaperHeight() {
        return paperHeight;
    }

    public void setPaperHeight(float paperHeight) {
        this.paperHeight = paperHeight;
    }

    public float getPaperWidth() {
        return paperWidth;
    }

    public void setPaperWidth(float paperWidth) {
        this.paperWidth = paperWidth;
    }

    public List<PrintData> getPrintDat() {
        return printDat;
    }

    public void setPrintDat(List<PrintData> printDat) {
        this.printDat = printDat;
    }



    public void preparePrintData4Save() {
//        for(PrintData data: printDat){
//            data.setPrintTemplates(this);
//            printDatas.add(data);
//        }

        for (PrintData printData: printDatas.values()) {
            printData.setPrintTemplates(this);
            for(PrintDataTable printDataTable: printData.getPrintDataTables().values()){
                printDataTable.setPrintData(printData);
            }
            for(PrintDataPhrase printDataPhrase: printData.getPrintDataPhrases().values()){
                printDataPhrase.setPrintData(printData);
            }
        }
    }

//    public void setPrintData(ArrayList<PrintData> printData){
//        for(PrintData data: printData){
//            data.setPrintTemplates(this);
//            printDatas.add(data);
//        }
//    }

    public List<PrintData> getPrintData() {
        ArrayList<PrintData> result = new ArrayList<PrintData>();
        for (PrintData printData : printDatas.values()) {
            result.add(printData);
        }
        return result;
    }

//    public Set<PrintData> getPrintDatas() {
//        return printDatas;
//    }
//
//    public void setPrintDatas(Set<PrintData> printDatas) {
//        this.printDatas = printDatas;
//    }

    public Set<RoutePrintTemplates> getRoutePrintTemplateses() {
        return routePrintTemplateses;
    }

    public void setRoutePrintTemplateses(Set<RoutePrintTemplates> routePrintTemplateses) {
        this.routePrintTemplateses = routePrintTemplateses;
    }

    public PrintTemplates() {
	}

    public PrintTemplates(Long hid, DocDir docDir, Date dattr, String un, String trans, Date altered, boolean defaults, float paperWidth,
                          float paperHeight, byte fontSize/*, boolean bold, boolean uppercase*/) {
        this.hid = hid;
        this.docDir = docDir;
        this.dattr = dattr;
        this.un = un;
        this.trans = trans;
        this.altered = altered;
        this.defaults = defaults;
        this.paperWidth = paperWidth;
        this.paperHeight = paperHeight;
        this.fontSize = fontSize;
//        this.bold = bold;
//        this.uppercase = uppercase;
    }

    public PrintTemplates(Long hid, DocDir docDir, String name, Date dattr, String un, String trans, Date altered, boolean defaults,
                          float paperWidth, float paperHeight, byte fontSize, /*boolean bold, boolean uppercase,*/ Set routePrintTemplateses, Map printDatas) {
        this.hid = hid;
        this.docDir = docDir;
        this.name = name;
        this.dattr = dattr;
        this.un = un;
        this.trans = trans;
        this.altered = altered;
        this.defaults = defaults;
        this.paperWidth = paperWidth;
        this.paperHeight = paperHeight;
        this.fontSize = fontSize;
//        this.bold = bold;
//        this.uppercase = uppercase;
        this.routePrintTemplateses = routePrintTemplateses;
        this.printDatas = printDatas;
    }

	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	public DocDir getDocDir() {
		return this.docDir;
	}

	public void setDocDir(DocDir docDir) {
		this.docDir = docDir;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

	public String getTrans() {
		return this.trans;
	}

	public void setTrans(String trans) {
		this.trans = trans;
	}

	public Date getAltered() {
		return this.altered;
	}

	public void setAltered(Date altered) {
		this.altered = altered;
	}

	public boolean isDefaults() {
		return this.defaults;
	}

	public void setDefaults(boolean defaults) {
		this.defaults = defaults;
	}

    public String buildRoutes() {
        StringBuilder sb = new StringBuilder();
        String prefix = "";
        for (RoutePrintTemplates router : routePrintTemplateses) {
            sb.append(prefix);
            prefix = ",";
            sb.append(router.getRoute().getName());
        }
        return sb.toString();
    }

    public boolean isDefaultable() {
        return defaultable;
    }

    public void setDefaultable(boolean defaultable) {
        this.defaultable = defaultable;
    }

    public void bindRoutes(List<Route> routes) {
        setRoutePrintTemplateses(new HashSet<RoutePrintTemplates>(0));
        if(routes != null){
            for(Route route : routes){
                getRoutePrintTemplateses().add(new RoutePrintTemplates(new RoutePrintTemplatesId(hid, route.getHid())));
            }
        }
    }

    public Set<RouteUnPrintTemplates> getRouteUnPrintTemplateses() {
        return routeUnPrintTemplateses;
    }

    public void setRouteUnPrintTemplateses(Set<RouteUnPrintTemplates> routeUnPrintTemplateses) {
        this.routeUnPrintTemplateses = routeUnPrintTemplateses;
    }
}
