package com.bivc.cimsmgs.db;

// Generated 13.05.2011 15:11:19 by Hibernate Tools 3.4.0.CR1

/**
 * ProjectGroupsId generated by hbm2java
 */
public class ProjectGroupsId implements java.io.Serializable {

	private Long hidProj;
	private String groupId;

	public ProjectGroupsId() {
	}

	public ProjectGroupsId(Long hidProj, String groupId) {
		this.hidProj = hidProj;
		this.groupId = groupId;
	}

	public Long getHidProj() {
		return this.hidProj;
	}

	public void setHidProj(Long hidProj) {
		this.hidProj = hidProj;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectGroupsId))
			return false;
		ProjectGroupsId castOther = (ProjectGroupsId) other;

		return ((this.getHidProj() == castOther.getHidProj()) || (this.getHidProj() != null && castOther.getHidProj() != null && this.getHidProj()
				.equals(castOther.getHidProj())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null && castOther.getGroupId() != null && this
						.getGroupId().equals(castOther.getGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHidProj() == null ? 0 : this.getHidProj().hashCode());
		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		return result;
	}

}
