package com.bivc.cimsmgs.db;

// Generated 13.05.2011 15:11:19 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.*;

import java.io.Serializable;

/**
 * RouteGroups generated by hbm2java
 */
@JsonIgnoreProperties({"id"})
public class RouteGroups implements Serializable {

	private RouteGroupsId id;
	private Route route;
    private UsrGroupsDir usrGroupsDir;

    public UsrGroupsDir getUsrGroupsDir() {
        return usrGroupsDir;
    }

    public void setUsrGroupsDir(UsrGroupsDir usrGroupsDir) {
        this.usrGroupsDir = usrGroupsDir;
    }

    public RouteGroups() {
	}

	public RouteGroups(RouteGroupsId id, Route route, UsrGroupsDir usrGroupsDir) {
		this.id = id;
		this.route = route;
        this.usrGroupsDir = usrGroupsDir;
	}

    public RouteGroups(Route route, UsrGroupsDir usrGroupsDir) {
        // Set fields
        this.route = route;
        this.usrGroupsDir = usrGroupsDir;
        // Set identifier values
        this.id = new RouteGroupsId();
        this.id.setGroupId(usrGroupsDir.getName());
        this.id.setHidRoute(route.getHid());
        // Guarantee referential integrity
        usrGroupsDir.getRouteGroupses().add(this);
        route.getRouteGroupses().add(this);
    }

	public RouteGroupsId getId() {
		return this.id;
	}

	public void setId(RouteGroupsId id) {
		this.id = id;
	}
    @JsonBackReference
	public Route getRoute() {
		return this.route;
	}
    @JsonBackReference
	public void setRoute(Route route) {
		this.route = route;
	}

}
