package com.bivc.cimsmgs.db;

// Generated 12.07.2012 14:46:29 by Hibernate Tools 3.4.0.CR1

/**
 * RoutePrintTemplates generated by hbm2java
 */
public class RoutePrintTemplates implements java.io.Serializable {

	private RoutePrintTemplatesId id;
	private PrintTemplates printTemplates;
	private Route route;

	public RoutePrintTemplates() {
	}

	public RoutePrintTemplates(RoutePrintTemplatesId id, PrintTemplates printTemplates, Route route) {
        this.id = id;
        this.printTemplates = printTemplates;
        this.route = route;
    }

    public RoutePrintTemplates(RoutePrintTemplatesId id) {
        this.id = id;
    }

	public RoutePrintTemplatesId getId() {
		return this.id;
	}

	public void setId(RoutePrintTemplatesId id) {
		this.id = id;
	}

	public PrintTemplates getPrintTemplates() {
		return this.printTemplates;
	}

	public void setPrintTemplates(PrintTemplates printTemplates) {
		this.printTemplates = printTemplates;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

}
