package com.bivc.cimsmgs.db;

// Generated 04.10.2012 7:53:09 by Hibernate Tools 3.4.0.CR1

/**
 * RouteUnPrintTemplates generated by hbm2java
 */
public class RouteUnPrintTemplates implements java.io.Serializable {

	private RouteUnPrintTemplatesId id;
	private PrintTemplates printTemplates;
	private Route route;
	private Usr usr;

	public RouteUnPrintTemplates() {
	}

	public RouteUnPrintTemplates(RouteUnPrintTemplatesId id, PrintTemplates printTemplates, Route route, Usr usr) {
		this.id = id;
		this.printTemplates = printTemplates;
		this.route = route;
		this.usr = usr;
	}

    public RouteUnPrintTemplates(RouteUnPrintTemplatesId id) {
        this.id = id;
    }

	public RouteUnPrintTemplatesId getId() {
		return this.id;
	}

	public void setId(RouteUnPrintTemplatesId id) {
		this.id = id;
	}

	public PrintTemplates getPrintTemplates() {
		return this.printTemplates;
	}

	public void setPrintTemplates(PrintTemplates printTemplates) {
		this.printTemplates = printTemplates;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

}
