package com.bivc.cimsmgs.db;

// Generated 12.07.2012 14:46:29 by Hibernate Tools 3.4.0.CR1

/**
 * RoutePrintTemplatesId generated by hbm2java
 */
public class RoutePrintTemplatesId implements java.io.Serializable {

	private Long hidPrnTmpl;
	private Long hidRoute;

	public RoutePrintTemplatesId() {
	}

	public RoutePrintTemplatesId(Long hidPrnTmpl, Long hidRoute) {
		this.hidPrnTmpl = hidPrnTmpl;
		this.hidRoute = hidRoute;
	}

	public Long getHidPrnTmpl() {
		return this.hidPrnTmpl;
	}

	public void setHidPrnTmpl(Long hidPrnTmpl) {
		this.hidPrnTmpl = hidPrnTmpl;
	}

	public Long getHidRoute() {
		return this.hidRoute;
	}

	public void setHidRoute(Long hidRoute) {
		this.hidRoute = hidRoute;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoutePrintTemplatesId))
			return false;
		RoutePrintTemplatesId castOther = (RoutePrintTemplatesId) other;

		return ((this.getHidPrnTmpl() == castOther.getHidPrnTmpl()) || (this.getHidPrnTmpl() != null && castOther.getHidPrnTmpl() != null && this
				.getHidPrnTmpl().equals(castOther.getHidPrnTmpl())))
				&& ((this.getHidRoute() == castOther.getHidRoute()) || (this.getHidRoute() != null && castOther.getHidRoute() != null && this
						.getHidRoute().equals(castOther.getHidRoute())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHidPrnTmpl() == null ? 0 : this.getHidPrnTmpl().hashCode());
		result = 37 * result + (getHidRoute() == null ? 0 : this.getHidRoute().hashCode());
		return result;
	}

}
