package com.bivc.cimsmgs.db;

// Generated 17.05.2011 9:39:56 by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.*;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * RouteDoc generated by hbm2java
 */
@JsonIgnoreProperties({"id"})
public class RouteDoc implements Serializable {

	private RouteDocId id;
	private Route route;
	private DocDir docDir;
    private BigDecimal sortId;

    public BigDecimal getSortId() {
        return sortId;
    }

    public void setSortId(BigDecimal sortId) {
        this.sortId = sortId;
    }

    public RouteDoc() {
	}

	public RouteDoc(RouteDocId id, Route route, DocDir docDir) {
		this.id = id;
		this.route = route;
		this.docDir = docDir;
	}

    public RouteDoc(Route route, DocDir docDir, BigDecimal sortId) {
        // Set fields
        this.route = route;
        this.docDir = docDir;
        this.sortId = sortId;
        // Set identifier values
        this.id = new RouteDocId();
        this.id.setHidDdir(docDir.getHid());
        this.id.setHidRoute(route.getHid());
        // Guarantee referential integrity
        docDir.getRouteDocs().add(this);
        route.getRouteDocs().add(this);
    }

	public RouteDocId getId() {
		return this.id;
	}

	public void setId(RouteDocId id) {
		this.id = id;
	}
    @JsonBackReference
	public Route getRoute() {
		return this.route;
	}
    @JsonBackReference
	public void setRoute(Route route) {
		this.route = route;
	}

	public DocDir getDocDir() {
		return this.docDir;
	}

	public void setDocDir(DocDir docDir) {
		this.docDir = docDir;
	}

}
