package com.bivc.cimsmgs.db;

// Generated 07.02.2012 15:44:00 by Hibernate Tools 3.4.0.CR1

import com.bivc.cimsmgs.commons.myUser;
import com.bivc.cimsmgs.db.nsi.Management;
import com.bivc.cimsmgs.db.nsi.Road;

import java.io.Serializable;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 * StaE generated by hbm2java
 */
public class StaE implements Serializable {

	private Long stUn;
	private Long stId;
	private String staNo;
	private String staName;
	/*private Integer managNo;
	private Integer roadNo;*/
	private String divNo;
	private String provNo;
	private Integer prPort;
	private Integer sign;
	private String gaugeKind;
	private String stWork;
	private String paragraph;
	private Date stBgn;
	private Date stEnd;
    private Road road;
    private Management management;
    private String staNameCh;
    private String staNameEn;

    public String getStaNameEn() {
        return staNameEn;
    }

    public void setStaNameEn(String staNameEn) {
        this.staNameEn = staNameEn;
    }

    public String getStaNameCh() {
        return staNameCh;
    }

    public void setStaNameCh(String staNameCh) {
        this.staNameCh = staNameCh;
    }

    public Management getManagement() {
        return management;
    }

    public void setManagement(Management management) {
        this.management = management;
    }

    public Road getRoad() {
        return road;
    }

    public void setRoad(Road road) {
        this.road = road;
    }

    public StaE() {
	}

	public StaE(long stUn) {
		this.stUn = stUn;
	}

	public StaE(long stUn, Long stId, String staNo, String staName,
			Integer managNo, Integer roadNo, String divNo, String provNo,
			Integer prPort, Integer sign, String gaugeKind, String stWork,
			String paragraph, Date stBgn, Date stEnd) {
		this.stUn = stUn;
		this.stId = stId;
		this.staNo = staNo;
		this.staName = staName;
//		this.managNo = managNo;
//		this.roadNo = roadNo;
		this.divNo = divNo;
		this.provNo = provNo;
		this.prPort = prPort;
		this.sign = sign;
		this.gaugeKind = gaugeKind;
		this.stWork = stWork;
		this.paragraph = paragraph;
		this.stBgn = stBgn;
		this.stEnd = stEnd;
	}

	public Long getStUn() {
		return this.stUn;
	}

	public void setStUn(Long stUn) {
		this.stUn = stUn;
	}

	public Long getStId() {
		return this.stId;
	}

	public void setStId(Long stId) {
		this.stId = stId;
	}

	public String getStaNo() {
		return this.staNo;
	}

	public void setStaNo(String staNo) {
		this.staNo = staNo;
	}

	public String getStaName() {
		return this.staName;
	}

	public void setStaName(String staName) {
		this.staName = staName;
	}

	/*public Integer getManagNo() {
		return this.managNo;
	}

	public void setManagNo(Integer managNo) {
		this.managNo = managNo;
	}

	public Integer getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(Integer roadNo) {
		this.roadNo = roadNo;
	}*/

	public String getDivNo() {
		return this.divNo;
	}

	public void setDivNo(String divNo) {
		this.divNo = divNo;
	}

	public String getProvNo() {
		return this.provNo;
	}

	public void setProvNo(String provNo) {
		this.provNo = provNo;
	}

	public Integer getPrPort() {
		return this.prPort;
	}

	public void setPrPort(Integer prPort) {
		this.prPort = prPort;
	}

	public Integer getSign() {
		return this.sign;
	}

	public void setSign(Integer sign) {
		this.sign = sign;
	}

	public String getGaugeKind() {
		return this.gaugeKind;
	}

	public void setGaugeKind(String gaugeKind) {
		this.gaugeKind = gaugeKind;
	}

	public String getStWork() {
		return this.stWork;
	}

	public void setStWork(String stWork) {
		this.stWork = stWork;
	}

	public String getParagraph() {
		return this.paragraph;
	}

	public void setParagraph(String paragraph) {
		this.paragraph = paragraph;
	}

	public Date getStBgn() {
		return this.stBgn;
	}

	public void setStBgn(Date stBgn) {
		this.stBgn = stBgn;
	}

	public Date getStEnd() {
		return this.stEnd;
	}

	public void setStEnd(Date stEnd) {
		this.stEnd = stEnd;
	}

    public void prepare4save(myUser user) {
        setStBgn(new Date(System.currentTimeMillis() - 1000*60*60*24));
        setStEnd(new GregorianCalendar(3000,1,1).getTime());
        //To change body of created methods use File | Settings | File Templates.
    }
}
