package com.bivc.cimsmgs.db;

// Generated 16.04.2012 15:44:53 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * StatusDir generated by hbm2java
 */
public class StatusDir implements Serializable {

	private BigDecimal hid;
	private String name;
	private String prim;
	private Set statuses = new HashSet(0);
    private String nameDe;
    private String primDe;

    public String getPrimDe() {
        return primDe;
    }

    public void setPrimDe(String primDe) {
        this.primDe = primDe;
    }

    public String getNameDe() {
        return nameDe;
    }

    public void setNameDe(String nameDe) {
        this.nameDe = nameDe;
    }

    public StatusDir() {
	}

	public StatusDir(BigDecimal hid) {
		this.hid = hid;
	}

	public StatusDir(BigDecimal hid, String name, String prim, Set statuses, String nameDe, String primDE) {
		this.hid = hid;
		this.name = name;
		this.prim = prim;
        this.nameDe = nameDe;
        this.primDe = primDe;
		this.statuses = statuses;
	}

	public BigDecimal getHid() {
		return this.hid;
	}

	public void setHid(BigDecimal hid) {
		this.hid = hid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	public Set getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set statuses) {
		this.statuses = statuses;
	}

}
