package com.bivc.cimsmgs.db;

// Generated 12.11.2010 16:44:31 by Hibernate Tools 3.4.0.Beta1

/**
 * UsrGroupsId generated by hbm2java
 */
public class UsrGroupsId implements java.io.Serializable {

	private String usrId;
	private String groupId;

	public UsrGroupsId() {
	}

	public UsrGroupsId(String usrId, String groupId) {
		this.usrId = usrId;
		this.groupId = groupId;
	}

	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrGroupsId))
			return false;
		UsrGroupsId castOther = (UsrGroupsId) other;

		return ((this.getUsrId() == castOther.getUsrId()) || (this.getUsrId() != null && castOther.getUsrId() != null && this.getUsrId().equals(
				castOther.getUsrId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null && castOther.getGroupId() != null && this
						.getGroupId().equals(castOther.getGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsrId() == null ? 0 : this.getUsrId().hashCode());
		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		return result;
	}

}
