package com.bivc.cimsmgs.db;

// Generated 12.11.2010 16:44:31 by Hibernate Tools 3.4.0.Beta1

/**
 * UsrPrivilegs generated by hbm2java
 */
public class UsrPrivilegs implements java.io.Serializable {

	private UsrPrivilegsId id;
	private UsrPrivilegsDir privileg;
	private Usr usr;

	public UsrPrivilegs() {
	}

	public UsrPrivilegs(UsrPrivilegsId id, UsrPrivilegsDir usrPrivilegsDir, Usr usr) {
		this.id = id;
		this.privileg = usrPrivilegsDir;
		this.usr = usr;
	}

	public UsrPrivilegsId getId() {
		return this.id;
	}

	public void setId(UsrPrivilegsId id) {
		this.id = id;
	}

	public UsrPrivilegsDir getPrivileg() {
		return this.privileg;
	}

	public void setPrivileg(UsrPrivilegsDir usrPrivilegsDir) {
		this.privileg = usrPrivilegsDir;
	}

	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

}
