SELECT kyys.NAME AS sectorName, CASE WHEN k.HID_VAGON IS NOT NULL THEN kyv.NVAG WHEN k.HID_AVTO IS NOT NULL THEN kya.NO_AVTO ELSE '' END AS location,
       CASE WHEN k.HID_VAGON IS NOT NULL THEN kyv.DIRECTION WHEN k.HID_AVTO IS NOT NULL THEN kya.DIRECTION ELSE NULL END AS direction,
       k.NKON AS nkon, k.MASSA_TAR AS massa_tar, k.MASSA_BRUTTO AS massa_brutto, k.MASSA_BRUTTO_ALL AS massa_brutto_all,
       k.POD_SILA AS pod_sila, k.VID AS vid, kyp.NPPRM AS npprm, k.DPRB AS dprb, k.DOTP AS dotp, cl.FNAME AS clientName, CAST(NULL AS SIGNED) AS kyDays
FROM KY_KONT k
         JOIN NSI_CLIENT cl ON k.HID_CLIENT = cl.HID
         JOIN NSI_CLIENT_GROUPS clg ON clg.HID_CLIENT=cl.HID
         LEFT JOIN KY_YARD kyy ON k.HID_KY = kyy.HID
         LEFT JOIN KY_YARD_SECTOR kyys ON kyy.HID_SECTOR = kyys.HID
         LEFT JOIN KY_VAGON kyv ON k.HID_VAGON = kyv.HID
         LEFT JOIN KY_POEZD kyp ON kyv.HID_POEZD = kyp.HID
         LEFT JOIN KY_AVTO kya ON k.HID_AVTO = kya.HID
WHERE
    (   k.HID_VAGON IS NOT NULL AND (k.DOTP IS NULL OR k.DOTP>SYSDATE()) AND EXISTS(SELECT p.hid FROM KY_POEZD p JOIN KY_VAGON v ON v.HID_POEZD = p.HID AND p.HID_ROUTE=? WHERE k.HID_VAGON = v.HID)
        OR k.HID_KY IS NOT NULL AND EXISTS(SELECT kys.hid FROM KY_YARD_SECTOR kys JOIN KY_YARD ky ON ky.HID_SECTOR = kys.HID AND kys.HID_ROUTE=? WHERE k.HID_KY = ky.HID)
        OR k.HID_AVTO IS NOT NULL AND (k.DOTP IS NULL OR k.DOTP>SYSDATE()) AND EXISTS(SELECT a.hid FROM KY_AVTO a WHERE k.HID_AVTO = a.HID  AND a.HID_ROUTE=?)
        ) AND (k.IS_ZAJAV IS NULL OR k.IS_ZAJAV = 0)
