SELECT K.HID AS HID_K, K.NKON, K.VID, K.POD_SILA, K.MASSA_TAR, K.STATUS,
  P.NPPR,V.NVAG,V.POD_SILA AS POD_SILA_V,V.MAS_TAR FROM KY_KONT K
  LEFT JOIN KY_POEZD P ON P.HID=K.HID_POEZD_OUT
  LEFT JOIN KY_VAGON V ON V.HID=K.HID_VAGON_OUT
WHERE K.HID_VAGON_INTO=?
