SELECT A.NVAG, A.DPRB, CASE WHEN A.PORUZ = 1 THEN 'P' ELSE 'L' END AS PORUZ, A.SOBSTV, A.REVIZ, A.PROBEG, P.DOTP, A.PRIM FROM KY_VAGON A
  JOIN KY_POEZD P ON P.DIRECTION=2 AND A.HID_POEZD=P.HID AND A.NVAG=? AND A.DOTP > ?
WHERE A.DOTP = (SELECT MIN(B.DOTP) FROM KY_VAGON B WHERE B.NVAG=? AND B.DIRECTION=2 AND B.DOTP > ?)