SELECT V.NVAG,K.HID,K.NKON,K.VID,K.POD_SILA,K.MASSA_TAR,K.PRIM FROM KY_POEZD P, KY_VAGON V, KY_KONT K
WHERE P.DIRECTION=1 AND P.KOLEYA=? AND P.HID=K.HID_POEZD_INTO
AND V.HID=K.HID_VAGON_INTO AND K.STATUS=1 AND K.HID_OWNER=? AND V.LINE=? AND P.DPRB=?
