package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * Cliaddress generated by hbm2java
 */
public class Cliaddress implements java.io.Serializable {

	private BigDecimal id;
	private Clientscompany clientscompany;
	private Country country;
	private String street;
	private String zip;
	private String city;
	private String email;
	private String addressType;
	private String phones;
	private String fax;

	public Cliaddress() {
	}

	public Cliaddress(BigDecimal id, Clientscompany clientscompany,
			Country country, String addressType) {
		this.id = id;
		this.clientscompany = clientscompany;
		this.country = country;
		this.addressType = addressType;
	}

	public Cliaddress(BigDecimal id, Clientscompany clientscompany,
			Country country, String street, String zip, String city,
			String email, String addressType, String phones, String fax) {
		this.id = id;
		this.clientscompany = clientscompany;
		this.country = country;
		this.street = street;
		this.zip = zip;
		this.city = city;
		this.email = email;
		this.addressType = addressType;
		this.phones = phones;
		this.fax = fax;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Clientscompany getClientscompany() {
		return this.clientscompany;
	}

	public void setClientscompany(Clientscompany clientscompany) {
		this.clientscompany = clientscompany;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	public String getPhones() {
		return this.phones;
	}

	public void setPhones(String phones) {
		this.phones = phones;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

}
