package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * Clicompanycontact generated by hbm2java
 */
public class Clicompanycontact implements java.io.Serializable {

	private BigDecimal id;
	private Clientscompany clientscompany;
	private String contactType;
	private String name;
	private String jobTitle;
	private String phones;
	private String mobPhone;

	public Clicompanycontact() {
	}

	public Clicompanycontact(BigDecimal id, Clientscompany clientscompany,
			String contactType, String name, String jobTitle) {
		this.id = id;
		this.clientscompany = clientscompany;
		this.contactType = contactType;
		this.name = name;
		this.jobTitle = jobTitle;
	}

	public Clicompanycontact(BigDecimal id, Clientscompany clientscompany,
			String contactType, String name, String jobTitle, String phones,
			String mobPhone) {
		this.id = id;
		this.clientscompany = clientscompany;
		this.contactType = contactType;
		this.name = name;
		this.jobTitle = jobTitle;
		this.phones = phones;
		this.mobPhone = mobPhone;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Clientscompany getClientscompany() {
		return this.clientscompany;
	}

	public void setClientscompany(Clientscompany clientscompany) {
		this.clientscompany = clientscompany;
	}

	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public String getPhones() {
		return this.phones;
	}

	public void setPhones(String phones) {
		this.phones = phones;
	}

	public String getMobPhone() {
		return this.mobPhone;
	}

	public void setMobPhone(String mobPhone) {
		this.mobPhone = mobPhone;
	}

}
