package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientscompany generated by hbm2java
 */
public class Clientscompany implements java.io.Serializable {

	private BigDecimal id;
	private Company company;
	private Country country;
	private BigDecimal sysclientId;
	private String clientRoles;
	private String smgs1;
	private String smgs5;
	private String vatcode;
	private String regcode;
	private String name;
	private String loginsAllowed;
	private String nameLatin1;
	private String isActive;
	private String digSignature;
	private Set<Clicompanycontact> clicompanycontacts = new HashSet<Clicompanycontact>(
			0);
	private Set<Cliaddress> cliaddresses = new HashSet<Cliaddress>(0);
	private Set<Clibankaccount> clibankaccounts = new HashSet<Clibankaccount>(0);
	private Set<Clientrailcode> clientrailcodes = new HashSet<Clientrailcode>(0);

	public Clientscompany() {
	}

	public Clientscompany(BigDecimal id, Company company, Country country,
			BigDecimal sysclientId, String clientRoles, String regcode,
			String name, String loginsAllowed, String nameLatin1,
			String isActive) {
		this.id = id;
		this.company = company;
		this.country = country;
		this.sysclientId = sysclientId;
		this.clientRoles = clientRoles;
		this.regcode = regcode;
		this.name = name;
		this.loginsAllowed = loginsAllowed;
		this.nameLatin1 = nameLatin1;
		this.isActive = isActive;
	}

	public Clientscompany(BigDecimal id, Company company, Country country,
			BigDecimal sysclientId, String clientRoles, String smgs1,
			String smgs5, String vatcode, String regcode, String name,
			String loginsAllowed, String nameLatin1, String isActive,
			String digSignature, Set<Clicompanycontact> clicompanycontacts,
			Set<Cliaddress> cliaddresses, Set<Clibankaccount> clibankaccounts,
			Set<Clientrailcode> clientrailcodes) {
		this.id = id;
		this.company = company;
		this.country = country;
		this.sysclientId = sysclientId;
		this.clientRoles = clientRoles;
		this.smgs1 = smgs1;
		this.smgs5 = smgs5;
		this.vatcode = vatcode;
		this.regcode = regcode;
		this.name = name;
		this.loginsAllowed = loginsAllowed;
		this.nameLatin1 = nameLatin1;
		this.isActive = isActive;
		this.digSignature = digSignature;
		this.clicompanycontacts = clicompanycontacts;
		this.cliaddresses = cliaddresses;
		this.clibankaccounts = clibankaccounts;
		this.clientrailcodes = clientrailcodes;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public BigDecimal getSysclientId() {
		return this.sysclientId;
	}

	public void setSysclientId(BigDecimal sysclientId) {
		this.sysclientId = sysclientId;
	}

	public String getClientRoles() {
		return this.clientRoles;
	}

	public void setClientRoles(String clientRoles) {
		this.clientRoles = clientRoles;
	}

	public String getSmgs1() {
		return this.smgs1;
	}

	public void setSmgs1(String smgs1) {
		this.smgs1 = smgs1;
	}

	public String getSmgs5() {
		return this.smgs5;
	}

	public void setSmgs5(String smgs5) {
		this.smgs5 = smgs5;
	}

	public String getVatcode() {
		return this.vatcode;
	}

	public void setVatcode(String vatcode) {
		this.vatcode = vatcode;
	}

	public String getRegcode() {
		return this.regcode;
	}

	public void setRegcode(String regcode) {
		this.regcode = regcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLoginsAllowed() {
		return this.loginsAllowed;
	}

	public void setLoginsAllowed(String loginsAllowed) {
		this.loginsAllowed = loginsAllowed;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public String getDigSignature() {
		return this.digSignature;
	}

	public void setDigSignature(String digSignature) {
		this.digSignature = digSignature;
	}

	public Set<Clicompanycontact> getClicompanycontacts() {
		return this.clicompanycontacts;
	}

	public void setClicompanycontacts(Set<Clicompanycontact> clicompanycontacts) {
		this.clicompanycontacts = clicompanycontacts;
	}

	public Set<Cliaddress> getCliaddresses() {
		return this.cliaddresses;
	}

	public void setCliaddresses(Set<Cliaddress> cliaddresses) {
		this.cliaddresses = cliaddresses;
	}

	public Set<Clibankaccount> getClibankaccounts() {
		return this.clibankaccounts;
	}

	public void setClibankaccounts(Set<Clibankaccount> clibankaccounts) {
		this.clibankaccounts = clibankaccounts;
	}

	public Set<Clientrailcode> getClientrailcodes() {
		return this.clientrailcodes;
	}

	public void setClientrailcodes(Set<Clientrailcode> clientrailcodes) {
		this.clientrailcodes = clientrailcodes;
	}

}
