package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private String code;
	private Currency currency;
	private BigDecimal id;
	private String name;
	private Short codeInt;
	private String nameLatin1;
	private String pdImport;
	private String pdExport;
	private String pdTransit;
	private String sendDecl;
	private String presentsCustomsCodes;
	private String smgsInstruction;
	private String invoiceInstruction;
	private Set<Bankaccount> bankaccounts = new HashSet<Bankaccount>(0);
	private Set<Customcode> customcodes = new HashSet<Customcode>(0);
	private Set<Company> companies = new HashSet<Company>(0);
	private Set<Clientscompany> clientscompanies = new HashSet<Clientscompany>(
			0);
	private Set<Clibankaccount> clibankaccounts = new HashSet<Clibankaccount>(0);
	private Set<Railroadland> railroadlands = new HashSet<Railroadland>(0);
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<Railroadstation> railroadstationsForCountryCode = new HashSet<Railroadstation>(
			0);
	private Set<Railroadstation> railroadstationsForLinkCountryCode = new HashSet<Railroadstation>(
			0);
	private Set<Cliaddress> cliaddresses = new HashSet<Cliaddress>(0);
  public Country() {
	}

	public Country(String code, Currency currency, BigDecimal id, String name,
			String nameLatin1, String pdImport, String pdExport,
			String pdTransit, String sendDecl, String presentsCustomsCodes) {
		this.code = code;
		this.currency = currency;
		this.id = id;
		this.name = name;
		this.nameLatin1 = nameLatin1;
		this.pdImport = pdImport;
		this.pdExport = pdExport;
		this.pdTransit = pdTransit;
		this.sendDecl = sendDecl;
		this.presentsCustomsCodes = presentsCustomsCodes;
	}

	public Country(String code, Currency currency, BigDecimal id, String name,
			Short codeInt, String nameLatin1, String pdImport, String pdExport,
			String pdTransit, String sendDecl, String presentsCustomsCodes,
			String smgsInstruction, String invoiceInstruction,
			Set<Bankaccount> bankaccounts, Set<Customcode> customcodes,
			Set<Company> companies, Set<Clientscompany> clientscompanies,
			Set<Clibankaccount> clibankaccounts,
			Set<Railroadland> railroadlands, Set<Address> addresses,
			Set<Railroadstation> railroadstationsForCountryCode,
			Set<Railroadstation> railroadstationsForLinkCountryCode,
			Set<Cliaddress> cliaddresses) {
		this.code = code;
		this.currency = currency;
		this.id = id;
		this.name = name;
		this.codeInt = codeInt;
		this.nameLatin1 = nameLatin1;
		this.pdImport = pdImport;
		this.pdExport = pdExport;
		this.pdTransit = pdTransit;
		this.sendDecl = sendDecl;
		this.presentsCustomsCodes = presentsCustomsCodes;
		this.smgsInstruction = smgsInstruction;
		this.invoiceInstruction = invoiceInstruction;
		this.bankaccounts = bankaccounts;
		this.customcodes = customcodes;
		this.companies = companies;
		this.clientscompanies = clientscompanies;
		this.clibankaccounts = clibankaccounts;
		this.railroadlands = railroadlands;
		this.addresses = addresses;
		this.railroadstationsForCountryCode = railroadstationsForCountryCode;
		this.railroadstationsForLinkCountryCode = railroadstationsForLinkCountryCode;
		this.cliaddresses = cliaddresses;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getCodeInt() {
		return this.codeInt;
	}

	public void setCodeInt(Short codeInt) {
		this.codeInt = codeInt;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public String getPdImport() {
		return this.pdImport;
	}

	public void setPdImport(String pdImport) {
		this.pdImport = pdImport;
	}

	public String getPdExport() {
		return this.pdExport;
	}

	public void setPdExport(String pdExport) {
		this.pdExport = pdExport;
	}

	public String getPdTransit() {
		return this.pdTransit;
	}

	public void setPdTransit(String pdTransit) {
		this.pdTransit = pdTransit;
	}

	public String getSendDecl() {
		return this.sendDecl;
	}

	public void setSendDecl(String sendDecl) {
		this.sendDecl = sendDecl;
	}

	public String getPresentsCustomsCodes() {
		return this.presentsCustomsCodes;
	}

	public void setPresentsCustomsCodes(String presentsCustomsCodes) {
		this.presentsCustomsCodes = presentsCustomsCodes;
	}

	public String getSmgsInstruction() {
		return this.smgsInstruction;
	}

	public void setSmgsInstruction(String smgsInstruction) {
		this.smgsInstruction = smgsInstruction;
	}

	public String getInvoiceInstruction() {
		return this.invoiceInstruction;
	}

	public void setInvoiceInstruction(String invoiceInstruction) {
		this.invoiceInstruction = invoiceInstruction;
	}

	public Set<Bankaccount> getBankaccounts() {
		return this.bankaccounts;
	}

	public void setBankaccounts(Set<Bankaccount> bankaccounts) {
		this.bankaccounts = bankaccounts;
	}

	public Set<Customcode> getCustomcodes() {
		return this.customcodes;
	}

	public void setCustomcodes(Set<Customcode> customcodes) {
		this.customcodes = customcodes;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

	public Set<Clientscompany> getClientscompanies() {
		return this.clientscompanies;
	}

	public void setClientscompanies(Set<Clientscompany> clientscompanies) {
		this.clientscompanies = clientscompanies;
	}

	public Set<Clibankaccount> getClibankaccounts() {
		return this.clibankaccounts;
	}

	public void setClibankaccounts(Set<Clibankaccount> clibankaccounts) {
		this.clibankaccounts = clibankaccounts;
	}

	public Set<Railroadland> getRailroadlands() {
		return this.railroadlands;
	}

	public void setRailroadlands(Set<Railroadland> railroadlands) {
		this.railroadlands = railroadlands;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	public Set<Railroadstation> getRailroadstationsForCountryCode() {
		return this.railroadstationsForCountryCode;
	}

	public void setRailroadstationsForCountryCode(
			Set<Railroadstation> railroadstationsForCountryCode) {
		this.railroadstationsForCountryCode = railroadstationsForCountryCode;
	}

	public Set<Railroadstation> getRailroadstationsForLinkCountryCode() {
		return this.railroadstationsForLinkCountryCode;
	}

	public void setRailroadstationsForLinkCountryCode(
			Set<Railroadstation> railroadstationsForLinkCountryCode) {
		this.railroadstationsForLinkCountryCode = railroadstationsForLinkCountryCode;
	}

	public Set<Cliaddress> getCliaddresses() {
		return this.cliaddresses;
	}

  public void setCliaddresses(Set<Cliaddress> cliaddresses) {
		this.cliaddresses = cliaddresses;
	}

}
