package com.bivc.cimsmgs.db.nsi;

// Generated 08.04.2011 10:06:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Countrys generated by hbm2java
 */
public class Countrys implements java.io.Serializable {

	private Long couUn;
	private Long couId;
	private String countryNo;
	private String region;
	private String countryId;
	private String countryName;
	private String countryFullname;
	private String countryId3;
	private String countryOkrb;
	private Date couBgn;
	private Date couEnd;

	public Countrys() {
	}

	public Countrys(Long couUn) {
		this.couUn = couUn;
	}

	public Countrys(Long couUn, Long couId, String countryNo, String region, String countryId, String countryName, String countryFullname,
			String countryId3, String countryOkrb, Date couBgn, Date couEnd) {
		this.couUn = couUn;
		this.couId = couId;
		this.countryNo = countryNo;
		this.region = region;
		this.countryId = countryId;
		this.countryName = countryName;
		this.countryFullname = countryFullname;
		this.countryId3 = countryId3;
		this.countryOkrb = countryOkrb;
		this.couBgn = couBgn;
		this.couEnd = couEnd;
	}

	public Long getCouUn() {
		return this.couUn;
	}

	public void setCouUn(Long couUn) {
		this.couUn = couUn;
	}

	public Long getCouId() {
		return this.couId;
	}

	public void setCouId(Long couId) {
		this.couId = couId;
	}

	public String getCountryNo() {
		return this.countryNo;
	}

	public void setCountryNo(String countryNo) {
		this.countryNo = countryNo;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getCountryFullname() {
		return this.countryFullname;
	}

	public void setCountryFullname(String countryFullname) {
		this.countryFullname = countryFullname;
	}

	public String getCountryId3() {
		return this.countryId3;
	}

	public void setCountryId3(String countryId3) {
		this.countryId3 = countryId3;
	}

	public String getCountryOkrb() {
		return this.countryOkrb;
	}

	public void setCountryOkrb(String countryOkrb) {
		this.countryOkrb = countryOkrb;
	}

	public Date getCouBgn() {
		return this.couBgn;
	}

	public void setCouBgn(Date couBgn) {
		this.couBgn = couBgn;
	}

	public Date getCouEnd() {
		return this.couEnd;
	}

	public void setCouEnd(Date couEnd) {
		this.couEnd = couEnd;
	}

}
