package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private String code;
	private BigDecimal id;
	private Short numCode;
	private String name;
	private String nameLatin1;
	private Set<Country> countries = new HashSet<Country>(0);

	public Currency() {
	}

	public Currency(String code, BigDecimal id, String name, String nameLatin1) {
		this.code = code;
		this.id = id;
		this.name = name;
		this.nameLatin1 = nameLatin1;
	}

	public Currency(String code, BigDecimal id, Short numCode, String name,
			String nameLatin1, Set<Country> countries) {
		this.code = code;
		this.id = id;
		this.numCode = numCode;
		this.name = name;
		this.nameLatin1 = nameLatin1;
		this.countries = countries;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Short getNumCode() {
		return this.numCode;
	}

	public void setNumCode(Short numCode) {
		this.numCode = numCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public Set<Country> getCountries() {
		return this.countries;
	}

	public void setCountries(Set<Country> countries) {
		this.countries = countries;
	}

}
