package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Customcode generated by hbm2java
 */
public class Customcode implements java.io.Serializable {

	private BigDecimal id;
	private Country country;
	private String mlName;
	private String nameLatin1;
	private String code;
	private String impName;
	private String impCode;
	private String recState;
	private Date workFrom;
	private Date workTill;
	private String digest;
	private String impId;
	private String impParentId;
	private String impHasCode;

	public Customcode() {
	}

	public Customcode(BigDecimal id, Country country, String mlName,
			String nameLatin1, String code, String recState, Date workFrom) {
		this.id = id;
		this.country = country;
		this.mlName = mlName;
		this.nameLatin1 = nameLatin1;
		this.code = code;
		this.recState = recState;
		this.workFrom = workFrom;
	}

	public Customcode(BigDecimal id, Country country, String mlName,
			String nameLatin1, String code, String impName, String impCode,
			String recState, Date workFrom, Date workTill, String digest,
			String impId, String impParentId, String impHasCode) {
		this.id = id;
		this.country = country;
		this.mlName = mlName;
		this.nameLatin1 = nameLatin1;
		this.code = code;
		this.impName = impName;
		this.impCode = impCode;
		this.recState = recState;
		this.workFrom = workFrom;
		this.workTill = workTill;
		this.digest = digest;
		this.impId = impId;
		this.impParentId = impParentId;
		this.impHasCode = impHasCode;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getMlName() {
		return this.mlName;
	}

	public void setMlName(String mlName) {
		this.mlName = mlName;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getImpName() {
		return this.impName;
	}

	public void setImpName(String impName) {
		this.impName = impName;
	}

	public String getImpCode() {
		return this.impCode;
	}

	public void setImpCode(String impCode) {
		this.impCode = impCode;
	}

	public String getRecState() {
		return this.recState;
	}

	public void setRecState(String recState) {
		this.recState = recState;
	}

	public Date getWorkFrom() {
		return this.workFrom;
	}

	public void setWorkFrom(Date workFrom) {
		this.workFrom = workFrom;
	}

	public Date getWorkTill() {
		return this.workTill;
	}

	public void setWorkTill(Date workTill) {
		this.workTill = workTill;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public String getImpId() {
		return this.impId;
	}

	public void setImpId(String impId) {
		this.impId = impId;
	}

	public String getImpParentId() {
		return this.impParentId;
	}

	public void setImpParentId(String impParentId) {
		this.impParentId = impParentId;
	}

	public String getImpHasCode() {
		return this.impHasCode;
	}

	public void setImpHasCode(String impHasCode) {
		this.impHasCode = impHasCode;
	}

}
