package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Karantin generated by hbm2java
 */
public class DangCode implements Serializable {

  private String code;
  private String descr;

  public String getDescr() {
    return descr;
  }

  public void setDescr(String descr) {
    this.descr = descr;
  }

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BigDecimal getHid() {
    return hid;
  }

  public void setHid(BigDecimal hid) {
    this.hid = hid;
  }

  private BigDecimal hid;

	public DangCode() {
	}

	public DangCode(BigDecimal hid) {
		this.hid = hid;
	}

}
