package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * Doctype generated by hbm2java
 */
public class Doctype implements java.io.Serializable {

	private BigDecimal id;
	private String code;
	private String name;
	private String nameLatin1;

	public Doctype() {
	}

	public Doctype(BigDecimal id, String code, String name, String nameLatin1) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.nameLatin1 = nameLatin1;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

}
