package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * GngUn generated by hbm2java
 */
public class GngUn implements java.io.Serializable {

	private BigDecimal id;
	private String unNum;
	private Long gngCode;
	private String cargoName;
	private String class_;
	private String classCode;
	private String dangerSign;
	private String cartNumb;

	public GngUn() {
	}

	public GngUn(BigDecimal id) {
		this.id = id;
	}

	public GngUn(BigDecimal id, String unNum, Long gngCode, String cargoName,
			String class_, String classCode, String dangerSign, String cartNumb) {
		this.id = id;
		this.unNum = unNum;
		this.gngCode = gngCode;
		this.cargoName = cargoName;
		this.class_ = class_;
		this.classCode = classCode;
		this.dangerSign = dangerSign;
		this.cartNumb = cartNumb;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getUnNum() {
		return this.unNum;
	}

	public void setUnNum(String unNum) {
		this.unNum = unNum;
	}

	public Long getGngCode() {
		return this.gngCode;
	}

	public void setGngCode(Long gngCode) {
		this.gngCode = gngCode;
	}

	public String getCargoName() {
		return this.cargoName;
	}

	public void setCargoName(String cargoName) {
		this.cargoName = cargoName;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getDangerSign() {
		return this.dangerSign;
	}

	public void setDangerSign(String dangerSign) {
		this.dangerSign = dangerSign;
	}

	public String getCartNumb() {
		return this.cartNumb;
	}

	public void setCartNumb(String cartNumb) {
		this.cartNumb = cartNumb;
	}

}
