package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Railroadstation generated by hbm2java
 */
public class Railroadstation implements java.io.Serializable {

	private BigDecimal id;
	private Railroadstation railroadstation;
	private Railroadland railroadland;
	private Railroad railroad;
	private Country countryByLinkCountryCode;
	private Country countryByCountryCode;
	private String code;
	private String mlName;
	private String nameLatin1;
	private String impKod;
	private String impNewcode;
	private String impName;
	private String impNewname;
	private String impNewparat;
	private String impParagtxt;
	private String impRoad;
	private String impLand;
	private String impLinkcode;
	private String recState;
	private Date workFrom;
	private Date workTill;
	private String digest;
	private Set<Railroadstation> railroadstations = new HashSet<Railroadstation>(
			0);
  public Railroadstation() {
	}

	public Railroadstation(BigDecimal id, Railroadland railroadland,
			Railroad railroad, String code, String mlName, String nameLatin1,
			String recState, Date workFrom) {
		this.id = id;
		this.railroadland = railroadland;
		this.railroad = railroad;
		this.code = code;
		this.mlName = mlName;
		this.nameLatin1 = nameLatin1;
		this.recState = recState;
		this.workFrom = workFrom;
	}

	public Railroadstation(BigDecimal id, Railroadstation railroadstation,
			Railroadland railroadland, Railroad railroad,
			Country countryByLinkCountryCode, Country countryByCountryCode,
			String code, String mlName, String nameLatin1, String impKod,
			String impNewcode, String impName, String impNewname,
			String impNewparat, String impParagtxt, String impRoad,
			String impLand, String impLinkcode, String recState, Date workFrom,
			Date workTill, String digest, Set<Railroadstation> railroadstations) {
		this.id = id;
		this.railroadstation = railroadstation;
		this.railroadland = railroadland;
		this.railroad = railroad;
		this.countryByLinkCountryCode = countryByLinkCountryCode;
		this.countryByCountryCode = countryByCountryCode;
		this.code = code;
		this.mlName = mlName;
		this.nameLatin1 = nameLatin1;
		this.impKod = impKod;
		this.impNewcode = impNewcode;
		this.impName = impName;
		this.impNewname = impNewname;
		this.impNewparat = impNewparat;
		this.impParagtxt = impParagtxt;
		this.impRoad = impRoad;
		this.impLand = impLand;
		this.impLinkcode = impLinkcode;
		this.recState = recState;
		this.workFrom = workFrom;
		this.workTill = workTill;
		this.digest = digest;
		this.railroadstations = railroadstations;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Railroadstation getRailroadstation() {
		return this.railroadstation;
	}

	public void setRailroadstation(Railroadstation railroadstation) {
		this.railroadstation = railroadstation;
	}

	public Railroadland getRailroadland() {
		return this.railroadland;
	}

	public void setRailroadland(Railroadland railroadland) {
		this.railroadland = railroadland;
	}

	public Railroad getRailroad() {
		return this.railroad;
	}

	public void setRailroad(Railroad railroad) {
		this.railroad = railroad;
	}

	public Country getCountryByLinkCountryCode() {
		return this.countryByLinkCountryCode;
	}

	public void setCountryByLinkCountryCode(Country countryByLinkCountryCode) {
		this.countryByLinkCountryCode = countryByLinkCountryCode;
	}

	public Country getCountryByCountryCode() {
		return this.countryByCountryCode;
	}

	public void setCountryByCountryCode(Country countryByCountryCode) {
		this.countryByCountryCode = countryByCountryCode;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMlName() {
		return this.mlName;
	}

	public void setMlName(String mlName) {
		this.mlName = mlName;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public String getImpKod() {
		return this.impKod;
	}

	public void setImpKod(String impKod) {
		this.impKod = impKod;
	}

	public String getImpNewcode() {
		return this.impNewcode;
	}

	public void setImpNewcode(String impNewcode) {
		this.impNewcode = impNewcode;
	}

	public String getImpName() {
		return this.impName;
	}

	public void setImpName(String impName) {
		this.impName = impName;
	}

	public String getImpNewname() {
		return this.impNewname;
	}

	public void setImpNewname(String impNewname) {
		this.impNewname = impNewname;
	}

	public String getImpNewparat() {
		return this.impNewparat;
	}

	public void setImpNewparat(String impNewparat) {
		this.impNewparat = impNewparat;
	}

	public String getImpParagtxt() {
		return this.impParagtxt;
	}

	public void setImpParagtxt(String impParagtxt) {
		this.impParagtxt = impParagtxt;
	}

	public String getImpRoad() {
		return this.impRoad;
	}

	public void setImpRoad(String impRoad) {
		this.impRoad = impRoad;
	}

	public String getImpLand() {
		return this.impLand;
	}

	public void setImpLand(String impLand) {
		this.impLand = impLand;
	}

	public String getImpLinkcode() {
		return this.impLinkcode;
	}

	public void setImpLinkcode(String impLinkcode) {
		this.impLinkcode = impLinkcode;
	}

	public String getRecState() {
		return this.recState;
	}

	public void setRecState(String recState) {
		this.recState = recState;
	}

	public Date getWorkFrom() {
		return this.workFrom;
	}

	public void setWorkFrom(Date workFrom) {
		this.workFrom = workFrom;
	}

	public Date getWorkTill() {
		return this.workTill;
	}

	public void setWorkTill(Date workTill) {
		this.workTill = workTill;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public Set<Railroadstation> getRailroadstations() {
		return this.railroadstations;
	}

  public void setRailroadstations(Set<Railroadstation> railroadstations) {
		this.railroadstations = railroadstations;
	}

}
