package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Railroadland generated by hbm2java
 */
public class Railroadland implements java.io.Serializable {

	private BigDecimal id;
	private Country country;
	private String mlName;
	private String impLname;
	private String impRname;
	private String impLandid;
	private String nameLatin1;
	private String landcode;
	private String landid;
	private String recState;
	private Date workFrom;
	private Date workTill;
	private String digest;
	private Set<Railroadstation> railroadstations = new HashSet<Railroadstation>(0);
	private Set<Clientrailcode> clientrailcodes = new HashSet<Clientrailcode>(0);
	private Set<Railroad> railroads = new HashSet<Railroad>(0);

  public Railroadland() {
	}

	public Railroadland(BigDecimal id, String mlName, String nameLatin1,
			String landid, String recState, Date workFrom) {
		this.id = id;
		this.mlName = mlName;
		this.nameLatin1 = nameLatin1;
		this.landid = landid;
		this.recState = recState;
		this.workFrom = workFrom;
	}

	public Railroadland(BigDecimal id, Country country, String mlName,
			String impLname, String impRname, String impLandid,
			String nameLatin1, String landcode, String landid, String recState,
			Date workFrom, Date workTill, String digest,
			Set<Railroadstation> railroadstations,
			Set<Clientrailcode> clientrailcodes, Set<Railroad> railroads) {
		this.id = id;
		this.country = country;
		this.mlName = mlName;
		this.impLname = impLname;
		this.impRname = impRname;
		this.impLandid = impLandid;
		this.nameLatin1 = nameLatin1;
		this.landcode = landcode;
		this.landid = landid;
		this.recState = recState;
		this.workFrom = workFrom;
		this.workTill = workTill;
		this.digest = digest;
		this.railroadstations = railroadstations;
		this.clientrailcodes = clientrailcodes;
		this.railroads = railroads;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getMlName() {
		return this.mlName;
	}

	public void setMlName(String mlName) {
		this.mlName = mlName;
	}

	public String getImpLname() {
		return this.impLname;
	}

	public void setImpLname(String impLname) {
		this.impLname = impLname;
	}

	public String getImpRname() {
		return this.impRname;
	}

	public void setImpRname(String impRname) {
		this.impRname = impRname;
	}

	public String getImpLandid() {
		return this.impLandid;
	}

	public void setImpLandid(String impLandid) {
		this.impLandid = impLandid;
	}

	public String getNameLatin1() {
		return this.nameLatin1;
	}

	public void setNameLatin1(String nameLatin1) {
		this.nameLatin1 = nameLatin1;
	}

	public String getLandcode() {
		return this.landcode;
	}

	public void setLandcode(String landcode) {
		this.landcode = landcode;
	}

	public String getLandid() {
		return this.landid;
	}

	public void setLandid(String landid) {
		this.landid = landid;
	}

	public String getRecState() {
		return this.recState;
	}

	public void setRecState(String recState) {
		this.recState = recState;
	}

	public Date getWorkFrom() {
		return this.workFrom;
	}

	public void setWorkFrom(Date workFrom) {
		this.workFrom = workFrom;
	}

	public Date getWorkTill() {
		return this.workTill;
	}

	public void setWorkTill(Date workTill) {
		this.workTill = workTill;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public Set<Railroadstation> getRailroadstations() {
		return this.railroadstations;
	}

	public void setRailroadstations(Set<Railroadstation> railroadstations) {
		this.railroadstations = railroadstations;
	}

	public Set<Clientrailcode> getClientrailcodes() {
		return this.clientrailcodes;
	}

	public void setClientrailcodes(Set<Clientrailcode> clientrailcodes) {
		this.clientrailcodes = clientrailcodes;
	}

	public Set<Railroad> getRailroads() {
		return this.railroads;
	}



  public void setRailroads(Set<Railroad> railroads) {
		this.railroads = railroads;
	}



}
