package com.bivc.cimsmgs.db.nsi;

// Generated 08.04.2011 10:06:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Road generated by hbm2java
 */
public class Road implements java.io.Serializable {

	private Long roadUn;
	private Long roadId;
//	private Integer managNo;
	private String roadNo;
	private String roadName;
	private String roadSname;
	private Date roadBgn;
	private Date roadEnd;
	private Management management;

	public Road() {
	}

	public Road(Long roadUn) {
		this.roadUn = roadUn;
	}

	public Road(Long roadUn, Long roadId, /*Integer managNo,*/ String roadNo, String roadName, String roadSname, Date roadBgn, Date roadEnd, Management management) {
		this.roadUn = roadUn;
		this.roadId = roadId;
//		this.managNo = managNo;
		this.roadNo = roadNo;
		this.roadName = roadName;
		this.roadSname = roadSname;
		this.roadBgn = roadBgn;
		this.roadEnd = roadEnd;
		this.management = management; 
	}

	public Long getRoadUn() {
		return this.roadUn;
	}

	public void setRoadUn(Long roadUn) {
		this.roadUn = roadUn;
	}

	public Long getRoadId() {
		return this.roadId;
	}

	public void setRoadId(Long roadId) {
		this.roadId = roadId;
	}

//	public Integer getManagNo() {
//		return this.managNo;
//	}
//
//	public void setManagNo(Integer managNo) {
//		this.managNo = managNo;
//	}

	public String getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	public String getRoadSname() {
		return this.roadSname;
	}

	public void setRoadSname(String roadSname) {
		this.roadSname = roadSname;
	}

	public Date getRoadBgn() {
		return this.roadBgn;
	}

	public void setRoadBgn(Date roadBgn) {
		this.roadBgn = roadBgn;
	}

	public Date getRoadEnd() {
		return this.roadEnd;
	}

	public void setRoadEnd(Date roadEnd) {
		this.roadEnd = roadEnd;
	}

	public void setManagement(Management management) {
		this.management = management;
	}

	public Management getManagement() {
		return management;
	}

}
