package com.bivc.cimsmgs.db.nsi;

// Generated 08.04.2011 10:06:32 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Sta generated by hbm2java
 */
public class Sta implements Serializable {

	private Long stUn;
	private Long stId;
	private String staNo;
	private String staName;
//	private Integer managNo;
//	private Integer roadNo;
	private String divNo;
	private String provNo;
	private Integer prPort;
	private Integer sign;
	private String gaugeKind;
	private String stWork;
	private String paragraph;
	private Date stBgn;
	private Date stEnd;
	private Road road;
	private Management management;
    private byte ro;
    private String staNameCh;
    private String staNameEn;

    public String getStaNameEn() {
        return staNameEn;
    }

    public void setStaNameEn(String staNameEn) {
        this.staNameEn = staNameEn;
    }

    public String getStaNameCh() {
        return staNameCh;
    }

    public void setStaNameCh(String staNameCh) {
        this.staNameCh = staNameCh;
    }

    public byte getRo() {
        return ro;
    }

    public void setRo(byte ro) {
        this.ro = ro;
    }

    public Sta() {
	}

	public Sta(Long stUn) {
		this.stUn = stUn;
	}

	public Sta(Long stUn, Long stId, String staNo, String staName, /*Integer managNo,*/ /*Integer roadNo,*/ String divNo, String provNo, Integer prPort,
			Integer sign, String gaugeKind, String stWork, String paragraph, Date stBgn, Date stEnd, Road road, Management management) {
		this.stUn = stUn;
		this.stId = stId;
		this.staNo = staNo;
		this.staName = staName;
//		this.managNo = managNo;
//		this.roadNo = roadNo;
		this.divNo = divNo;
		this.provNo = provNo;
		this.prPort = prPort;
		this.sign = sign;
		this.gaugeKind = gaugeKind;
		this.stWork = stWork;
		this.paragraph = paragraph;
		this.stBgn = stBgn;
		this.stEnd = stEnd;
		this.road = road;
		this.management = management;
	}

	public Long getStUn() {
		return this.stUn;
	}

	public void setStUn(Long stUn) {
		this.stUn = stUn;
	}

	public Long getStId() {
		return this.stId;
	}

	public void setStId(Long stId) {
		this.stId = stId;
	}

	public String getStaNo() {
		return this.staNo;
	}

	public void setStaNo(String staNo) {
		this.staNo = staNo;
	}

	public String getStaName() {
		return this.staName;
	}

	public void setStaName(String staName) {
		this.staName = staName;
	}

//	public Integer getManagNo() {
//		return this.managNo;
//	}
//
//	public void setManagNo(Integer managNo) {
//		this.managNo = managNo;
//	}

//	public Integer getRoadNo() {
//		return this.roadNo;
//	}
//
//	public void setRoadNo(Integer roadNo) {
//		this.roadNo = roadNo;
//	}

	public String getDivNo() {
		return this.divNo;
	}

	public void setDivNo(String divNo) {
		this.divNo = divNo;
	}

	public String getProvNo() {
		return this.provNo;
	}

	public void setProvNo(String provNo) {
		this.provNo = provNo;
	}

	public Integer getPrPort() {
		return this.prPort;
	}

	public void setPrPort(Integer prPort) {
		this.prPort = prPort;
	}

	public Integer getSign() {
		return this.sign;
	}

	public void setSign(Integer sign) {
		this.sign = sign;
	}

	public String getGaugeKind() {
		return this.gaugeKind;
	}

	public void setGaugeKind(String gaugeKind) {
		this.gaugeKind = gaugeKind;
	}

	public String getStWork() {
		return this.stWork;
	}

	public void setStWork(String stWork) {
		this.stWork = stWork;
	}

	public String getParagraph() {
		return this.paragraph;
	}

	public void setParagraph(String paragraph) {
		this.paragraph = paragraph;
	}

	public Date getStBgn() {
		return this.stBgn;
	}

	public void setStBgn(Date stBgn) {
		this.stBgn = stBgn;
	}

	public Date getStEnd() {
		return this.stEnd;
	}

	public void setStEnd(Date stEnd) {
		this.stEnd = stEnd;
	}

	public void setRoad(Road road) {
		this.road = road;
	}

	public Road getRoad() {
		return road;
	}

	public void setManagement(Management management) {
		this.management = management;
	}

	public Management getManagement() {
		return management;
	}

}
