package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import com.bivc.cimsmgs.db.CimSmgsStatus;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private BigDecimal id;
	private Company company;
	private String loginName;
	private Date allowedFrom;
	private Date allowedTo;
	private String jobTitle;
	private String phones;
	private String email;
	private String password;
	private Date nextPasswordChange;
	private String clockNumber;
	private String disabled;
	private String disabledMessage;
	private String name;
	private String surname;
	private String mobPhone;
	private String fax;
	private String locale;
	private String subscribedToCtmMaillist;
	private String isConnected;
	private String functionalPermissions;
  private Set<CimSmgsStatus> cimSmgsStatuses = new HashSet<CimSmgsStatus>(0);

	public Users() {
	}

	public Users(BigDecimal id, Company company, String loginName,
			String jobTitle, String password, String disabled, String name,
			String surname, String locale, String subscribedToCtmMaillist,
			String isConnected, Set<CimSmgsStatus> cimSmgsStatuses) {
		this.id = id;
		this.company = company;
		this.loginName = loginName;
		this.jobTitle = jobTitle;
		this.password = password;
		this.disabled = disabled;
		this.name = name;
		this.surname = surname;
		this.locale = locale;
		this.subscribedToCtmMaillist = subscribedToCtmMaillist;
		this.isConnected = isConnected;
    this.cimSmgsStatuses=cimSmgsStatuses;
	}

	public Users(BigDecimal id, Company company, String loginName,
			Date allowedFrom, Date allowedTo, String jobTitle, String phones,
			String email, String password, Date nextPasswordChange,
			String clockNumber, String disabled, String disabledMessage,
			String name, String surname, String mobPhone, String fax,
			String locale, String subscribedToCtmMaillist, String isConnected,
			String functionalPermissions) {
		this.id = id;
		this.company = company;
		this.loginName = loginName;
		this.allowedFrom = allowedFrom;
		this.allowedTo = allowedTo;
		this.jobTitle = jobTitle;
		this.phones = phones;
		this.email = email;
		this.password = password;
		this.nextPasswordChange = nextPasswordChange;
		this.clockNumber = clockNumber;
		this.disabled = disabled;
		this.disabledMessage = disabledMessage;
		this.name = name;
		this.surname = surname;
		this.mobPhone = mobPhone;
		this.fax = fax;
		this.locale = locale;
		this.subscribedToCtmMaillist = subscribedToCtmMaillist;
		this.isConnected = isConnected;
		this.functionalPermissions = functionalPermissions;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public Date getAllowedFrom() {
		return this.allowedFrom;
	}

	public void setAllowedFrom(Date allowedFrom) {
		this.allowedFrom = allowedFrom;
	}

	public Date getAllowedTo() {
		return this.allowedTo;
	}

	public void setAllowedTo(Date allowedTo) {
		this.allowedTo = allowedTo;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public String getPhones() {
		return this.phones;
	}

	public void setPhones(String phones) {
		this.phones = phones;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getNextPasswordChange() {
		return this.nextPasswordChange;
	}

	public void setNextPasswordChange(Date nextPasswordChange) {
		this.nextPasswordChange = nextPasswordChange;
	}

	public String getClockNumber() {
		return this.clockNumber;
	}

	public void setClockNumber(String clockNumber) {
		this.clockNumber = clockNumber;
	}

	public String getDisabled() {
		return this.disabled;
	}

	public void setDisabled(String disabled) {
		this.disabled = disabled;
	}

	public String getDisabledMessage() {
		return this.disabledMessage;
	}

	public void setDisabledMessage(String disabledMessage) {
		this.disabledMessage = disabledMessage;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMobPhone() {
		return this.mobPhone;
	}

	public void setMobPhone(String mobPhone) {
		this.mobPhone = mobPhone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getSubscribedToCtmMaillist() {
		return this.subscribedToCtmMaillist;
	}

	public void setSubscribedToCtmMaillist(String subscribedToCtmMaillist) {
		this.subscribedToCtmMaillist = subscribedToCtmMaillist;
	}

	public String getIsConnected() {
		return this.isConnected;
	}

	public void setIsConnected(String isConnected) {
		this.isConnected = isConnected;
	}

	public String getFunctionalPermissions() {
		return this.functionalPermissions;
	}

  public Set<CimSmgsStatus> getCimSmgsStatuses()
  {
    return cimSmgsStatuses;
  }

  public void setFunctionalPermissions(String functionalPermissions) {
		this.functionalPermissions = functionalPermissions;
	}

  public void setCimSmgsStatuses(Set<CimSmgsStatus> cimSmgsStatuses)
  {
    this.cimSmgsStatuses = cimSmgsStatuses;
  }

}
