package com.bivc.cimsmgs.db.nsi;

// Generated 22.04.2009 13:49:34 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * Karantin generated by hbm2java
 */
public class Veterin implements java.io.Serializable {

  public BigDecimal getHid() {
    return hid;
  }

  public void setHid(BigDecimal hid) {
    this.hid = hid;
  }

  private BigDecimal hid;
	private String kgvn;
	private String nzgr;

	public Veterin() {
	}

	public Veterin(BigDecimal hid) {
		this.hid = hid;
	}

	public Veterin(BigDecimal hid, String kgvn, String nzgr) {
		this.hid = hid;
		this.kgvn = kgvn;
		this.nzgr = nzgr;
	}


	public String getKgvn() {
		return this.kgvn;
	}

	public void setKgvn(String kgvn) {
		this.kgvn = kgvn;
	}

	public String getNzgr() {
		return this.nzgr;
	}

	public void setNzgr(String nzgr) {
		this.nzgr = nzgr;
	}

}
